### ISSUE TITLE
Epoll initialization can deadlock if done simultaneously with SSLContext

### ISSUE THREAD

**Issue by lidavidm** [netty/netty#10187]
### Expected behavior

Initializing Epoll concurrently with SSLContext will not deadlock.

### Actual behavior

Initializing Epoll concurrently with SSLContext can deadlock. This is very similar to #7458. That fixes a deadlock inside `netty_unix_socket.c`. The deadlock here is in `netty_linux_socket.c`.

What seems to happen is the following:

1. Thread 1 loads Netty epoll, which locks Runtime.class.
1. Thread 2 creates an SSLContext, which eventually tries to initialize sun.nio.ch.IOUtil. This holds IOUtil's class initialization lock.
1. IOUtil/thread 2 then tries to load the JVM "net" and "nio" native libraries, which tries to lock Runtime.class and blocks.
1. Thread 1 then tries to load sun.io.ch.FileChannelImpl, which also tries to load sun.nio.ch.IOUtil. Now the two threads are deadlocked.

https://github.com/netty/netty/blob/bdaa935756c3ae86f8b5353011d9682d5e247dcc/transport-native-epoll/src/main/c/netty_epoll_linuxsocket.c#L777

### Steps to reproduce

Try creating an SSLContext on one thread while loading Epoll on another thread.

### Minimal yet complete reproducer code (or URL to code)

No code, unfortunately - this was internal.

Stack traces:

```
"main" #1 prio=5 os_prio=0 cpu=1508.46ms elapsed=261.43s tid=0x000014d2d0040800 nid=0x32e634 waiting for monitor entry  [0x000014d2d7dd6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Runtime.loadLibrary0(java.base@11.0.6/Runtime.java:821)
	- waiting to lock <0x00000007b88cb060> (a java.lang.Runtime)
	at java.lang.System.loadLibrary(java.base@11.0.6/System.java:1870)
	at sun.nio.ch.IOUtil$1.run(java.base@11.0.6/IOUtil.java:438)
	at sun.nio.ch.IOUtil$1.run(java.base@11.0.6/IOUtil.java:436)
	at java.security.AccessController.doPrivileged(java.base@11.0.6/Native Method)
	at sun.nio.ch.IOUtil.<clinit>(java.base@11.0.6/IOUtil.java:435)
	at sun.nio.ch.FileChannelImpl.<clinit>(java.base@11.0.6/FileChannelImpl.java:1212)
	at sun.nio.fs.UnixChannelFactory.newFileChannel(java.base@11.0.6/UnixChannelFactory.java:144)
	at sun.nio.fs.UnixChannelFactory.newFileChannel(java.base@11.0.6/UnixChannelFactory.java:156)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(java.base@11.0.6/UnixFileSystemProvider.java:217)
	at java.nio.file.Files.newByteChannel(java.base@11.0.6/Files.java:370)
	at java.nio.file.Files.newByteChannel(java.base@11.0.6/Files.java:421)
	at java.nio.file.spi.FileSystemProvider.newInputStream(java.base@11.0.6/FileSystemProvider.java:420)
	at java.nio.file.Files.newInputStream(java.base@11.0.6/Files.java:155)
	at javax.crypto.JceSecurity.setupJurisdictionPolicies(java.base@11.0.6/JceSecurity.java:335)
	at javax.crypto.JceSecurity$1.run(java.base@11.0.6/JceSecurity.java:111)
	at javax.crypto.JceSecurity$1.run(java.base@11.0.6/JceSecurity.java:108)
	at java.security.AccessController.doPrivileged(java.base@11.0.6/Native Method)
	at javax.crypto.JceSecurity.<clinit>(java.base@11.0.6/JceSecurity.java:107)
	at javax.crypto.Cipher.getInstance(java.base@11.0.6/Cipher.java:540)
	at sun.security.ssl.JsseJce.getCipher(java.base@11.0.6/JsseJce.java:185)
	at sun.security.ssl.SSLCipher.isTransformationAvailable(java.base@11.0.6/SSLCipher.java:483)
	at sun.security.ssl.SSLCipher.<init>(java.base@11.0.6/SSLCipher.java:472)
	at sun.security.ssl.SSLCipher.<clinit>(java.base@11.0.6/SSLCipher.java:81)
	at sun.security.ssl.CipherSuite.<clinit>(java.base@11.0.6/CipherSuite.java:67)
	at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(java.base@11.0.6/SSLContextImpl.java:348)
	at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(java.base@11.0.6/SSLContextImpl.java:580)
	at java.lang.Class.forName0(java.base@11.0.6/Native Method)
	at java.lang.Class.forName(java.base@11.0.6/Class.java:315)
	at java.security.Provider$Service.getImplClass(java.base@11.0.6/Provider.java:1848)
	at java.security.Provider$Service.newInstance(java.base@11.0.6/Provider.java:1824)
	at sun.security.jca.GetInstance.getInstance(java.base@11.0.6/GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(java.base@11.0.6/GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(java.base@11.0.6/SSLContext.java:168)
	at javax.net.ssl.SSLContext.getDefault(java.base@11.0.6/SSLContext.java:99)
	- locked <0x00000007bb3f0528> (a java.lang.Class for javax.net.ssl.SSLContext)
	at javax.net.ssl.SSLSocketFactory.getDefault(java.base@11.0.6/SSLSocketFactory.java:123)
	- locked <0x00000007bb3f02e0> (a java.lang.Class for javax.net.ssl.SSLSocketFactory)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(java.base@11.0.6/HttpsURLConnection.java:335)
	at javax.net.ssl.HttpsURLConnection.<init>(java.base@11.0.6/HttpsURLConnection.java:292)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(java.base@11.0.6/HttpsURLConnectionImpl.java:100)
	at sun.net.www.protocol.https.Handler.openConnection(java.base@11.0.6/Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(java.base@11.0.6/Handler.java:57)
	at java.net.URL.openConnection(java.base@11.0.6/URL.java:1074)
```

```
"Thread-2" #30 prio=5 os_prio=0 cpu=65.77ms elapsed=259.92s tid=0x000014d2d1450800 nid=0x32e672 in Object.wait()  [0x000014d24d1a5000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ClassLoader$NativeLibrary.load0(java.base@11.0.6/Native Method)
	at java.lang.ClassLoader$NativeLibrary.load(java.base@11.0.6/ClassLoader.java:2430)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.6/ClassLoader.java:2487)
	- locked <0x00000007b8cf1178> (a java.util.HashSet)
	at java.lang.ClassLoader.loadLibrary0(java.base@11.0.6/ClassLoader.java:2684)
	at java.lang.ClassLoader.loadLibrary(java.base@11.0.6/ClassLoader.java:2649)
	at java.lang.Runtime.loadLibrary0(java.base@11.0.6/Runtime.java:829)
	- locked <0x00000007b88cb060> (a java.lang.Runtime)
	at java.lang.System.loadLibrary(java.base@11.0.6/System.java:1870)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.6/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.6/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.6/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.6/Method.java:566)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
	at java.security.AccessController.doPrivileged(java.base@11.0.6/Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:186)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:57)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:53)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:143)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:105)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:92)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:69)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:53)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:46)
```

### Netty version

4.1.39.Final

### JVM version (e.g. `java -version`)

OpenJDK 11.0.6

### OS version (e.g. `uname -a`)

Linux 4.14.67 on x86_64

**Comment by normanmaurer** [comment]
@lidavidm hmm... `findClass(...)` should never produce a deadlock. Can you please update to the latest netty version and try again ?

**Comment by lidavidm** [comment]
Let me try to get a minimal reproduction and get the GDB stack trace as well. There was definitely a deadlock inside the native initializer, but it's hard to reproduce. For us, explicitly forcing all static initializers to run before we actually started the app stopped the deadlock from occurring.

**Comment by lidavidm** [comment]
Okay, time for some debugger shennanigans.

```
package com.example;

import io.netty.channel.epoll.Epoll;

import javax.net.ssl.SSLContext;
import java.security.NoSuchAlgorithmException;

public class Main {
  public static void main(String[] args) throws Exception {
    final Thread thread1 = new Thread(() -> {
      try {
        SSLContext.getDefault();
      } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException(e);
      }
    });

    final Thread thread2 = new Thread(Epoll::ensureAvailability);

    thread2.start();
    thread1.start();
    thread1.join();
    thread2.join();
  }
}
```

Run this inside an IDE, then set breakpoints at the following places:

`ClassLoader.class` on the `load0` call

```
    boolean load() {
      if (this.handle != 0L) {
        throw new InternalError("Native library " + this.name + " has been loaded");
      } else if (!this.load0(this.name, this.isBuiltin)) {
        return false;
      } else {
```

`IOUtil.class` on the `doPrivileged` and `loadLibrary` call

```
    AccessController.doPrivileged(new PrivilegedAction<Void>() {
      public Void run() {
        System.loadLibrary("net");
```

Whichever breakpoint triggers first, resume the other thread only. Once both threads are at their breakpoints, first step the Netty thread, then step the IOUtil thread. The program will deadlock with the stacktrace above.

**Comment by lidavidm** [comment]
@normanmaurer here is the stack trace from GDB:

```
0x00007f5865ee5a67 in __pthread_clockjoin_ex () from /usr/lib/libpthread.so.0
(gdb) info thread
  Id   Target Id                                            Frame 
* 1    Thread 0x7f5865eda400 (LWP 162405) "java"            0x00007f5865ee5a67 in __pthread_clockjoin_ex () from /usr/lib/libpthread.so.0
  2    Thread 0x7f58649ba700 (LWP 162409) "java"            0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  3    Thread 0x7f5864646700 (LWP 162412) "GC Thread#0"     0x00007f5865eed7b4 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  4    Thread 0x7f584852c700 (LWP 162413) "G1 Main Marker"  0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  5    Thread 0x7f584842a700 (LWP 162414) "G1 Conc#0"       0x00007f5865eed7b4 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  6    Thread 0x7f5839a35700 (LWP 162415) "G1 Refine#0"     0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  7    Thread 0x7f5839933700 (LWP 162416) "G1 Young RemSet" 0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  8    Thread 0x7f5838f55700 (LWP 162417) "VM Thread"       0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  9    Thread 0x7f5838e53700 (LWP 162418) "Reference Handl" 0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  10   Thread 0x7f5838d52700 (LWP 162419) "Finalizer"       0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  11   Thread 0x7f583896b700 (LWP 162421) "Signal Dispatch" 0x00007f5865eed7b4 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  12   Thread 0x7f583886a700 (LWP 162422) "C2 CompilerThre" 0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  13   Thread 0x7f5838769700 (LWP 162423) "C1 CompilerThre" 0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  14   Thread 0x7f5838668700 (LWP 162424) "Sweeper thread"  0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  15   Thread 0x7f5838567700 (LWP 162431) "Common-Cleaner"  0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  16   Thread 0x7f5838365700 (LWP 162436) "JDWP Transport " 0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  17   Thread 0x7f5838264700 (LWP 162438) "JDWP Event Help" 0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  18   Thread 0x7f5838163700 (LWP 162439) "JDWP Command Re" 0x00007f586601c5fc in recv () from /usr/lib/libc.so.6
  19   Thread 0x7f5838466700 (LWP 162442) "Service Thread"  0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  20   Thread 0x7f57fbfff700 (LWP 162443) "VM Periodic Tas" 0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  21   Thread 0x7f57fbefd700 (LWP 162444) "Thread-1"        0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  22   Thread 0x7f57fbdfc700 (LWP 162445) "Thread-0"        0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  23   Thread 0x7f57fbcfb700 (LWP 162706) "Attach Listener" 0x00007f586601c3af in accept () from /usr/lib/libc.so.6
(gdb) t 21
[Switching to thread 21 (Thread 0x7f57fbefd700 (LWP 162444))]
#0  0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007f5865eeacf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f58658dd0f4 in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#2  0x00007f58658ae786 in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#3  0x00007f5865539060 in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#4  0x00007f5865615d13 in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#5  0x00007f58655d20c0 in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#6  0x00007f58480121c4 in netty_epoll_linuxsocket_JNI_OnLoad (env=env@entry=0x7f5860465b40, packagePrefix=packagePrefix@entry=0x0) at src/netty_epoll_linuxsocket.c:793
#7  0x00007f584800f93b in netty_epoll_native_JNI_OnLoad (env=0x7f5860465b40, packagePrefix=packagePrefix@entry=0x0) at src/netty_epoll_native.c:525
#8  0x00007f584800fde9 in JNI_OnLoad_netty_transport_native_epoll0 (vm=<optimized out>, reserved=<optimized out>) at src/netty_epoll_native.c:634
#9  0x00007f5848010674 in JNI_OnLoad (vm=<optimized out>, reserved=<optimized out>) at src/netty_epoll_native.c:668
#10 0x00007f5864890eab in Java_java_lang_ClassLoader_00024NativeLibrary_load0 () from /usr/lib/jvm/java-11-openjdk/lib/libjava.so
#11 0x00007f5848925297 in ?? ()
#12 0x00007f57fbef9660 in ?? ()
#13 0x00007f5848924e66 in ?? ()
#14 0x00007f5848924e21 in ?? ()
#15 0x00007f57fbef9618 in ?? ()
#16 0x00007f583946f0c8 in ?? ()
#17 0x00007f57fbef9690 in ?? ()
#18 0x00007f583946f8a8 in ?? ()
#19 0x0000000000000000 in ?? ()
(gdb) f 6
#6  0x00007f58480121c4 in netty_epoll_linuxsocket_JNI_OnLoad (env=env@entry=0x7f5860465b40, packagePrefix=packagePrefix@entry=0x0) at src/netty_epoll_linuxsocket.c:793
793	    jclass fileChannelCls = (*env)->FindClass(env, "sun/nio/ch/FileChannelImpl");
(gdb) t 22
[Switching to thread 22 (Thread 0x7f57fbdfc700 (LWP 162445))]
#0  0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007f5865eeb01a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f58658da99f in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#2  0x00007f58658ad12d in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#3  0x00007f58658ad7da in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#4  0x00007f5865550b12 in ?? () from /usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so
#5  0x00007f5848924154 in ?? ()
#6  0x00007f584892410f in ?? ()
#7  0x0000000000000003 in ?? ()
#8  0x0000000734b07aa0 in ?? ()
#9  0x00007f57fbdf4f28 in ?? ()
#10 0x00007f5839174c20 in ?? ()
#11 0x00007f57fbdf4fa8 in ?? ()
#12 0x00007f5839174f00 in ?? ()
#13 0x0000000000000000 in ?? ()
```

It seems `FindClass` does acquire a lock.

**Comment by johnou** [comment]
@lidavidm can you repro this with latest openjdk8?

**Comment by lidavidm** [comment]
@johnou no, I am not. I had to change the reproduction to use `Files.newByteChannel` instead of `SSLContext.getDefault` to hit the same breakpoints, and the breakpoint in `ClassLoader` is different:

```java
        ClassLoader.NativeLibrary var25 = new ClassLoader.NativeLibrary(var0, var2, var3);
        nativeLibraryContext.push(var25);

        try {
          var25.load(var2, var3); // break here conditional on var2.indexOf("epoll") > -1
        } finally {
          nativeLibraryContext.pop();
        }
```

I also forgot some details above for reproducing on JDK 11 - make the breakpoint in `ClassLoader` conditional on `this.name.indexOf("epoll") > -1`, and set breakpoints to pause only the thread.

**Comment by normanmaurer** [comment]
@lidavidm @johnou there is also this https://bugs.openjdk.java.net/browse/JDK-8231584 .... I wonder if its related

**Comment by lidavidm** [comment]
Yeah, in JDK8, it looks like `System.loadLibrary` doesn't hold the `Runtime` lock.

```
"Thread-1@659" prio=5 tid=0xe nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946)
	  - locked <0x35f> (a java.util.Vector)
	  - locked <0x157> (a java.util.Vector)
	  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1828)
	  at java.lang.Runtime.load0(Runtime.java:810)
	  at java.lang.System.load(System.java:1088)
	  at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
	  at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
	  at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:203)
	  at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:186)
	  at io.netty.channel.epoll.Native.<clinit>(Native.java:57)
	  at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	  at com.example.Main$$Lambda$2.451111351.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:748)

"Thread-0@660" prio=5 tid=0xd nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.IOUtil.<clinit>(IOUtil.java:356)
	  at sun.nio.ch.FileChannelImpl.<clinit>(FileChannelImpl.java:1218)
	  at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:137)
	  at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148)
	  at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:212)
	  at java.nio.file.Files.newByteChannel(Files.java:361)
	  at java.nio.file.Files.newByteChannel(Files.java:407)
	  at com.example.Main.lambda$main$0(Main.java:15)
	  at com.example.Main$$Lambda$1.1638215613.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:748)
```

**Comment by lidavidm** [comment]
(This is from stopping it in the debugger - both threads proceed normally once unpaused.)

**Comment by lidavidm** [comment]
Ah! So it seems this would be fixed by 11.0.7. https://bugs.openjdk.java.net/browse/JDK-8235261

AdoptOpenJDK will have builds ready soon, I can test those as well.

**Comment by lidavidm** [comment]
For my edification, how is this different than #7458? It seems to me they have the same underlying cause.

**Comment by normanmaurer** [comment]
@lidavidm at the end it is not I think... So #7458 only partly was fixed before I guess.

**Comment by normanmaurer** [comment]
@lidavidm let me know once you tested .

**Comment by lidavidm** [comment]
Unfortunately, the issue is still there :(  I just tested Azul's builds of OpenJDK 11.

```
> ./zulu11.39.15-ca-jdk11.0.7-linux_x64/bin/java -version                                                                                                                                                                              (base) 
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
```

This time, it deadlocks because even though we aren't locking Runtime, ClassLoader internally synchronizes a Map of loaded libraries to prevent double-loading.

JStack:

```
"Thread-1" #16 prio=5 os_prio=0 cpu=265.62ms elapsed=73.14s tid=0x00007fb5fc44b000 nid=0x2d1e5 in Object.wait()  [0x00007fb597be0000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ClassLoader$NativeLibrary.load0(java.base@11.0.7/Native Method)
	at java.lang.ClassLoader$NativeLibrary.load(java.base@11.0.7/ClassLoader.java:2442)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.7/ClassLoader.java:2498)
	- locked <0x0000000734b07648> (a java.util.HashSet)
	at java.lang.ClassLoader.loadLibrary0(java.base@11.0.7/ClassLoader.java:2694)
	at java.lang.ClassLoader.loadLibrary(java.base@11.0.7/ClassLoader.java:2627)
	at java.lang.Runtime.load0(java.base@11.0.7/Runtime.java:768)
	at java.lang.System.load(java.base@11.0.7/System.java:1834)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.7/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.7/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.7/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.7/Method.java:566)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
	at java.security.AccessController.doPrivileged(java.base@11.0.7/Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:203)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:186)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:57)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at com.example.Main$$Lambda$15/0x0000000800090040.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.7/Thread.java:834)

"Thread-0" #15 prio=5 os_prio=0 cpu=6.46ms elapsed=73.14s tid=0x00007fb5fc44d000 nid=0x2d1e6 waiting for monitor entry  [0x00007fb597adf000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.7/ClassLoader.java:2462)
	- waiting to lock <0x0000000734b07648> (a java.util.HashSet)
	at java.lang.ClassLoader.loadLibrary0(java.base@11.0.7/ClassLoader.java:2694)
	at java.lang.ClassLoader.loadLibrary(java.base@11.0.7/ClassLoader.java:2648)
	at java.lang.Runtime.loadLibrary0(java.base@11.0.7/Runtime.java:830)
	at java.lang.System.loadLibrary(java.base@11.0.7/System.java:1870)
	at sun.nio.ch.IOUtil$1.run(java.base@11.0.7/IOUtil.java:438)
	at sun.nio.ch.IOUtil$1.run(java.base@11.0.7/IOUtil.java:436)
	at java.security.AccessController.doPrivileged(java.base@11.0.7/Native Method)
	at sun.nio.ch.IOUtil.<clinit>(java.base@11.0.7/IOUtil.java:435)
	at sun.nio.ch.FileChannelImpl.<clinit>(java.base@11.0.7/FileChannelImpl.java:1212)
	at sun.nio.fs.UnixChannelFactory.newFileChannel(java.base@11.0.7/UnixChannelFactory.java:144)
	at sun.nio.fs.UnixChannelFactory.newFileChannel(java.base@11.0.7/UnixChannelFactory.java:156)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(java.base@11.0.7/UnixFileSystemProvider.java:217)
	at java.nio.file.Files.newByteChannel(java.base@11.0.7/Files.java:370)
	at java.nio.file.Files.newByteChannel(java.base@11.0.7/Files.java:421)
	at com.example.Main.lambda$main$0(Main.java:15)
	at com.example.Main$$Lambda$14/0x0000000800065840.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.7/Thread.java:834)
```

GDB:

```
#6  0x00007fb5971cd8f9 in netty_epoll_linuxsocket_JNI_OnLoad () from /tmp/libnetty_transport_native_epoll_x86_648392289424391927617.so
(gdb) info thread
  Id   Target Id                                            Frame 
  1    Thread 0x7fb6031cd040 (LWP 184764) "java"            0x00007fb6035b3a67 in __pthread_clockjoin_ex () from /usr/lib/libpthread.so.0
  2    Thread 0x7fb601bc8700 (LWP 184772) "java"            0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  3    Thread 0x7fb600c2b700 (LWP 184773) "GC Thread#0"     0x00007fb6035bb7b4 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  4    Thread 0x7fb600241700 (LWP 184774) "G1 Main Marker"  0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  5    Thread 0x7fb60013f700 (LWP 184775) "G1 Conc#0"       0x00007fb6035bb7b4 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  6    Thread 0x7fb5d5d38700 (LWP 184776) "G1 Refine#0"     0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  7    Thread 0x7fb5d5c36700 (LWP 184777) "G1 Young RemSet" 0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  8    Thread 0x7fb5d52b3700 (LWP 184781) "VM Thread"       0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  9    Thread 0x7fb5d51b1700 (LWP 184782) "Reference Handl" 0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  10   Thread 0x7fb5d50b0700 (LWP 184783) "Finalizer"       0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  11   Thread 0x7fb5d4cc9700 (LWP 184788) "Signal Dispatch" 0x00007fb6035bb7b4 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  12   Thread 0x7fb5d4bc8700 (LWP 184789) "C2 CompilerThre" 0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  13   Thread 0x7fb5d4ac7700 (LWP 184790) "C1 CompilerThre" 0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  14   Thread 0x7fb5d49c6700 (LWP 184791) "Sweeper thread"  0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  15   Thread 0x7fb5d48c5700 (LWP 184797) "Common-Cleaner"  0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  16   Thread 0x7fb5d45be700 (LWP 184798) "JDWP Transport " 0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  17   Thread 0x7fb5d44bd700 (LWP 184800) "JDWP Event Help" 0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  18   Thread 0x7fb5d43bc700 (LWP 184802) "JDWP Command Re" 0x00007fb6035bc9bc in recv () from /usr/lib/libpthread.so.0
  19   Thread 0x7fb597de7700 (LWP 184803) "Service Thread"  0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  20   Thread 0x7fb597ce6700 (LWP 184804) "VM Periodic Tas" 0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
* 21   Thread 0x7fb597be4700 (LWP 184805) "Thread-1"        0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  22   Thread 0x7fb597ae3700 (LWP 184806) "Thread-0"        0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  23   Thread 0x7fb5971c7700 (LWP 185004) "Attach Listener" 0x00007fb6035bc85f in accept () from /usr/lib/libpthread.so.0
(gdb) thread 21
[Switching to thread 21 (Thread 0x7fb597be4700 (LWP 184805))]
#6  0x00007fb5971cd8f9 in netty_epoll_linuxsocket_JNI_OnLoad () from /tmp/libnetty_transport_native_epoll_x86_648392289424391927617.so
(gdb) bt
#0  0x00007fb6035b8cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007fb60292ed43 in os::PlatformEvent::park() () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#2  0x00007fb6028fd3b5 in ObjectMonitor::wait(long, bool, Thread*) () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#3  0x00007fb60258746b in InstanceKlass::initialize_impl(Thread*) () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#4  0x00007fb602658436 in find_class_from_class_loader(JNIEnv_*, Symbol*, unsigned char, Handle, Handle, unsigned char, Thread*) () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#5  0x00007fb60262ce82 in jni_FindClass () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#6  0x00007fb5971cd8f9 in netty_epoll_linuxsocket_JNI_OnLoad () from /tmp/libnetty_transport_native_epoll_x86_648392289424391927617.so
#7  0x00007fb5971ce65a in JNI_OnLoad_netty_transport_native_epoll0 () from /tmp/libnetty_transport_native_epoll_x86_648392289424391927617.so
#8  0x00007fb60169106d in Java_java_lang_ClassLoader_00024NativeLibrary_load0 () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/libjava.so
#9  0x00007fb5e4698297 in ?? ()
#10 0x00007fb597be0650 in ?? ()
#11 0x00007fb5e4697e66 in ?? ()
#12 0x00007fb5e4697e21 in ?? ()
#13 0x00007fb597be0608 in ?? ()
#14 0x00007fb5d576e8e8 in ?? ()
#15 0x00007fb597be0680 in ?? ()
#16 0x00007fb5d576f0c8 in ?? ()
#17 0x0000000000000000 in ?? ()
(gdb) thread 22
[Switching to thread 22 (Thread 0x7fb597ae3700 (LWP 184806))]
#0  0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007fb6035b901a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007fb60292eece in os::PlatformEvent::park(long) () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#2  0x00007fb6028fcabc in ObjectMonitor::enter(Thread*) () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#3  0x00007fb6025a3646 in InterpreterRuntime::monitorenter(JavaThread*, BasicObjectLock*) () from /home/lidavidm/Code/twosigma/zulu11.39.15-ca-jdk11.0.7-linux_x64/lib/server/libjvm.so
#4  0x00007fb5e46af293 in ?? ()
#5  0x00007fb5e46af24e in ?? ()
#6  0x0000000000000003 in ?? ()
#7  0x0000000734b07648 in ?? ()
#8  0x00007fb597adfd98 in ?? ()
#9  0x00007fb5d576ec54 in ?? ()
#10 0x00007fb597adfe48 in ?? ()
#11 0x00007fb5d576f0c8 in ?? ()
#12 0x0000000000000000 in ?? ()
```
Azul appears to have some symbols - so we can clearly see we're waiting on a class initializer (though unfortunately the info about which class is unavailable - though that seems pretty clear)

**Comment by normanmaurer** [comment]
@lidavidm hmm... not sure what I can do about it :/

**Comment by lidavidm** [comment]
Would it make sense for Netty (in Java) to "touch" IOUtil somehow to force it to be loaded, before loading Netty's JNI library?

**Comment by lidavidm** [comment]
That is the workaround we resorted to - not pretty, but it works in practice.

**Comment by normanmaurer** [comment]
@lidavidm yeah I guess that is the best we can do... Let me come up with a pr.

**Comment by johnou** [comment]
@lidavidm since it's not fixed in 11.0.7 can you reach out to the openjdk devs on the mailing list?

**Comment by lidavidm** [comment]
Now that I look more closely, the JDK bug report is not quite what we are doing: we have a deadlock between findClass and loadLibrary, not findLibrary and loadLibrary. As in, here, we have somewhat of a circular dependency between two classes. Is this still worth reaching out to the mailing list about, or would it be considered user error? Though it does still seem to be a regression from JDK8.

**Comment by normanmaurer** [comment]
@lidavidm can you check https://github.com/netty/netty/pull/10190 ?

**Comment by lidavidm** [comment]
I will give it a test, thank you!

**Comment by johnou** [comment]
@lidavidm thanks for such a detailed bug report.

**Comment by lidavidm** [comment]
Thank you both for the quick response and suggestions!
