### ISSUE TITLE
[Question] DNS native resolver for Apple Silicon M1

### ISSUE THREAD

**Issue by NicklasWallgren** [netty/netty#11380]
Hey, 

Are there any available DNS resolvers for the new M1 processor?

```
Caused by: java.lang.UnsatisfiedLinkError: 'io.netty.resolver.dns.macos.DnsResolver[] io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.resolvers()'
```

**Comment by normanmaurer** [comment]
not at the moment... But I think we will provide one soonish

**Comment by NicklasWallgren** [comment]
Ah, great to hear. 

Has there been any progress on this, or are we still forced to run using rosetta? Thanks.

**Comment by normanmaurer** [comment]
unfortunally not yet.

**Comment by normanmaurer** [comment]
This was fixed in 4.1.68.Final

**Comment by NicklasWallgren** [comment]
Thanks

**Comment by johanreimann** [comment]
@normanmaurer I still get 

```
Caused by: java.lang.UnsatisfiedLinkError: 'io.netty.resolver.dns.macos.DnsResolver[] io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.resolvers()'
```
Using version 4.1.69.Final on a M1 processor

**Comment by chrisvest** [comment]
@johanreimann What classifier are you getting for the native dependency?

**Comment by johanreimann** [comment]
That was the problem! I didn't have a classifier specified.

It works when i specify it:
```
implementation 'io.netty:netty-resolver-dns-native-macos:4.1.70.Final:osx-aarch_64'
```

Thanks!
