### ISSUE TITLE
Add support for M1 Silicon Macs - Can't build Netty

### ISSUE THREAD

**Issue by tmulle** [netty/netty#12024]
I know the M1 Macs are still relatively new and not all developers have them, I decided to try to build Netty for the first time ever on my M1 Mac and it failed.

Just letting you know in case no one has tried before.

I also wonder if the NATIVE-TRANSPORTS (kqueue) will also build on M1 Macs?

### Expected behavior
To be able to run ```mvn clean package``` successfully

### Actual behavior
Build fails with error:

```
[INFO] Running io.netty.handler.codec.compression.BrotliEncoderTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in io.netty.handler.codec.compression.BrotliEncoderTest
[ERROR] io.netty.handler.codec.compression.BrotliEncoderTest  Time elapsed: 0 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at io.netty.handler.codec.compression.BrotliEncoderTest.<clinit>(BrotliEncoderTest.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.api.condition.MethodBasedCondition.invokeConditionMethod(MethodBasedCondition.java:82)
	at org.junit.jupiter.api.condition.MethodBasedCondition.lambda$evaluateExecutionCondition$1(MethodBasedCondition.java:52)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.junit.jupiter.api.condition.MethodBasedCondition.evaluateExecutionCondition(MethodBasedCondition.java:52)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:64)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.lambda$evaluate$0(ConditionEvaluator.java:55)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:57)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$checkWhetherSkipped$2(NodeTestTask.java:119)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.checkWhetherSkipped(NodeTestTask.java:119)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:81)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.UnsatisfiedLinkError: Failed to load Brotli native library
	at com.aayushatharva.brotli4j.Brotli4jLoader.ensureAvailability(Brotli4jLoader.java:78)
	at io.netty.handler.codec.compression.Brotli.ensureAvailability(Brotli.java:71)
	at io.netty.handler.codec.compression.BrotliEncoderTest.<clinit>(BrotliEncoderTest.java:33)
	... 53 more
Caused by: java.lang.UnsupportedOperationException: Unsupported OS and Architecture: Mac OS X, aarch64
	at com.aayushatharva.brotli4j.Brotli4jLoader.getPlatform(Brotli4jLoader.java:106)
	at com.aayushatharva.brotli4j.Brotli4jLoader.<clinit>(Brotli4jLoader.java:38)
	at io.netty.handler.codec.compression.Brotli.<clinit>(Brotli.java:46)
	at io.netty.handler.codec.compression.BrotliDecoderTest.<clinit>(BrotliDecoderTest.java:49)
	... 53 more
```

### Steps to reproduce
Clone Netty repo and run ```mvn clean package```

### JVM version (e.g. `java -version`)
JDk11 and JDK17

### OS version (e.g. `uname -a`)
21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by chrisvest** [comment]
It should work if you set up your development environment according to the [guide](https://netty.io/wiki/developer-guide.html).
This looks like it might be an issue with the optional brotli dependency? /cc @hyperxpro

**Comment by hyperxpro** [comment]
`Caused by: java.lang.UnsupportedOperationException: Unsupported OS and Architecture: Mac OS X, aarch64`

This is expected because Brotli4j is not supported on macOS aarch64. There is an open [PR](https://github.com/hyperxpro/Brotli4j/pull/34) for M1 support but GitHub Actions don't support M1 yet so it's not merged yet.

**Comment by normanmaurer** [comment]
Will have a look

**Comment by hyperxpro** [comment]
Alright, this test should not have been initialized on OSX aarch64.

@normanmaurer Is this on your list or I should fix this?

**Comment by normanmaurer** [comment]
@hyperxpro please do if you have time... I have some other stuff todo first.

**Comment by tmulle** [comment]
@normanmaurer  or @chrisvest I am trying to build Netty from source to test out your fix for my issue before 4.1.74 is released and I'm running into issues building.

On My ARM Mac I get a different error than my X86

**ARM**
When I run ```mvn clean install``` from the Netty main directory after a while the. build fails with:

```
[ERROR] Failed to execute goal on project netty-handler: Could not resolve dependencies for project io.netty:netty-handler:jar:4.1.74.Final-SNAPSHOT: io.netty:netty-tcnative:jar:osx-aarch_64:2.0.48.Final was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```


**INTEL X86**
The tests fail in Netty/Handler

```
[WARNING] Tests run: 9, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.607 s - in io.netty.handler.ssl.SniHandlerTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   JdkOpenSslEngineInteroptTest.checkOpenSsl:51 » UnsatisfiedLink failed to load ...
[ERROR]   OpenSslCachingKeyMaterialProviderTest>OpenSslKeyMaterialProviderTest.checkOpenSsl:48 » UnsatisfiedLink
[ERROR]   OpenSslCertificateExceptionTest.ensureOpenSsl:32 » UnsatisfiedLink failed to l...
[ERROR]   OpenSslClientContextTest.checkOpenSsl:28 » UnsatisfiedLink failed to load the ...
[ERROR]   OpenSslEngineTest.checkOpenSsl:94 » UnsatisfiedLink failed to load the require...
[ERROR]   OpenSslJdkSslEngineInteroptTest.checkOpenSsl:51 » UnsatisfiedLink failed to lo...
[ERROR]   OpenSslKeyMaterialManagerTest.testChooseClientAliasReturnsNull:36 » UnsatisfiedLink
[ERROR]   OpenSslKeyMaterialProviderTest.checkOpenSsl:48 » UnsatisfiedLink failed to loa...
[ERROR]   OpenSslRenegotiateTest.checkOpenSsl:32 » UnsatisfiedLink failed to load the re...
[ERROR]   OpenSslServerContextTest.checkOpenSsl:27 » UnsatisfiedLink failed to load the ...
[ERROR]   OpenSslX509KeyManagerFactoryProviderTest>OpenSslKeyMaterialProviderTest.checkOpenSsl:48 » UnsatisfiedLink
[ERROR]   PemEncodedTest.testPemEncodedOpenSsl:40->testPemEncoded:49 » UnsatisfiedLink f...
[ERROR]   PemEncodedTest.testPemEncodedOpenSslRef:45->testPemEncoded:49 » UnsatisfiedLink
[ERROR]   ReferenceCountedOpenSslEngineTest>OpenSslEngineTest.checkOpenSsl:94 » UnsatisfiedLink
[ERROR]   SslContextBuilderTest.testClientContextFromFileOpenssl:55 » UnsatisfiedLink fa...
[ERROR]   SslContextBuilderTest.testClientContextOpenssl:66 » UnsatisfiedLink failed to ...
[ERROR]   SslContextBuilderTest.testContextFromManagersOpenssl:110 » UnsatisfiedLink fai...
[ERROR]   SslContextBuilderTest.testInvalidCipherJdk:179 » UnsatisfiedLink failed to loa...
[ERROR]   SslContextBuilderTest.testInvalidCipherOpenSSL:190 » UnsatisfiedLink failed to...
[ERROR]   SslContextBuilderTest.testKeyStoreTypeOpenssl:77 » UnsatisfiedLink failed to l...
[ERROR]   SslContextBuilderTest.testServerContextFromFileOpenssl:88 » UnsatisfiedLink fa...
[ERROR]   SslContextBuilderTest.testServerContextOpenssl:99 » UnsatisfiedLink failed to ...
[ERROR]   SslErrorTest.testCorrectAlert » PreconditionViolation Configuration error: You...
[ERROR]   SslHandlerTest.testHandshakeEventsTls12Openssl:1674 » UnsatisfiedLink failed t...
[ERROR]   SslHandlerTest.testHandshakeEventsTls13Openssl:1686 » UnsatisfiedLink failed t...
[ERROR]   SslHandlerTest.testHandshakeFailureCipherMissmatchTLSv13OpenSsl:1562 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testHandshakeMTLSWithExecutorOpenSsl:1077 » UnsatisfiedLink fai...
[ERROR]   SslHandlerTest.testHandshakeMTLSWithExecutorThatExecuteDirectlyOpenSsl:1059 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testHandshakeMTLSWithImmediateEventExecutorOpenSsl:1071 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testHandshakeMTLSWithImmediateExecutorOpenSsl:1065 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testHandshakeWithExecutorOpenSsl:1023 » UnsatisfiedLink failed ...
[ERROR]   SslHandlerTest.testHandshakeWithExecutorThatExecuteDirectlyOpenSsl:1005 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testHandshakeWithImmediateEventExecutorOpenSsl:1017 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testHandshakeWithImmediateExecutorOpenSsl:1011 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testReleaseSslEngine:400 » UnsatisfiedLink failed to load the r...
[ERROR]   SslHandlerTest.testSessionTicketsWithTLSv12:1252->testSessionTickets:1276 » UnsatisfiedLink
[ERROR]   SslHandlerTest.testSessionTicketsWithTLSv12AndNoKey:1265->testSessionTickets:1276 » UnsatisfiedLink

	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:225)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
		... 58 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:167)
		... 59 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: /Users/tmulle/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
```

I see a bunch of these messages in the output, which seems to indicate the native libraries aren't being built in and installed as part of the main Netty build? 

I followed the instructions on BOTH machines to build the native transports, at least the little instructions that are there and not sure if I need to do anything else to get the libraries to build.

```Building the MacOS/BSD native transport
To build the native transport, you need to use MacOS 10.12 or higher. Please also install the required tools and libraries:

brew install autoconf automake libtool
```

**Comment by chrisvest** [comment]
@tmulle On MacOS/M1, try enabling the `-Pboringssl-osx-arch64` profile.

**Comment by tmulle** [comment]
@chrisvest Thanks..getting further (I think)...The build fails with this error, which looks related to the `Brotoli` libs..

```
Caused by: java.lang.IllegalStateException: Brotli is not available
        at io.netty.handler.codec.compression.BrotliOptions.<init>(BrotliOptions.java:38)
        at io.netty.handler.codec.compression.BrotliOptions.<clinit>(BrotliOptions.java:33)
        ... 67 more
Caused by: java.lang.UnsupportedOperationException: Unsupported OS and Architecture: Mac OS X, aarch64
        at com.aayushatharva.brotli4j.Brotli4jLoader.getPlatform(Brotli4jLoader.java:106)
        at com.aayushatharva.brotli4j.Brotli4jLoader.<clinit>(Brotli4jLoader.java:38)
        at io.netty.handler.codec.compression.Brotli.<clinit>(Brotli.java:46)
        at io.netty.handler.codec.http.HttpContentCompressor.<init>(HttpContentCompressor.java:174)
        at io.netty.handler.codec.http.HttpContentCompressor.<init>(HttpContentCompressor.java:153)
        at io.netty.handler.codec.http.HttpContentCompressorOptionsTest.testAcceptEncodingHttpRequest(HttpContentCompressorOptionsTest.java:88)
        ... 65 more

testGetZstdTargetContentEncoding  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.codec.compression.BrotliOptions
        at io.netty.handler.codec.compression.StandardCompressionOptions.brotli(StandardCompressionOptions.java:35)
        at io.netty.handler.codec.http.HttpContentCompressorOptionsTest.testGetZstdTargetContentEncoding(HttpContentCompressorOptionsTest.java:65)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by hyperxpro** [comment]
@tmulle This error was fixed in recent commit. Please rebase and try again.

**Comment by chenyyyang** [comment]
I find that this error still **not** be fixed when upgrade to 
 <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <classifier>osx-aarch_64</classifier>
            <version>4.1.78.Final</version>
        </dependency>

**Comment by xuwei-k** [comment]
- https://repo1.maven.org/maven2/com/aayushatharva/brotli4j/native-osx-aarch64/1.8.0/
- https://github.com/hyperxpro/Brotli4j/releases/tag/v1.8.0

> Apple Silicon M1 support
