### ISSUE TITLE
Potential optimization to findOutboundContext

### ISSUE THREAD

**Issue by mind-fuzzy** [netty/netty#13832]
[Moving the conversation from Discord channel to here for visibility and community input]

As part of `flush` and `write` calls it finds the outbound context which is currently implemented using a linked list resulting in pointer chasing and iterating it for every call.

This can have an impact in case the application has a high number of handlers or high volume of flush/writes. Some of the potential optimization discussed in the discord channel (Suggested by @forked_franz)

- have a different data structure from a linked list (having volatile prev fields) -> but is not easy (eg an unrolled list/or a copy on write array)

- have a form of caching for the jump -> but is not easy to keep it up-to-date unless we can "freeze" the pipeline, actually making it immutable temporarily

**Comment by RoganDawes** [comment]
Possibly stupid idea: keep individual linked lists for each operation (ChannelHandlerContext.nextWriteHandler, etc), which points to the next handler that actually overrides the method in question. These pointers would be updated when pipeline changes are made.

Changes the search for every read/write/etc into a one time operation, with a memory tradeoff (pointer for each method).

**Comment by normanmaurer** [comment]
In the main branch this is fixed but it's not something we can easily port to 4.1 sadly.

**Comment by mind-fuzzy** [comment]
Nice! Glad to hear that! 

If possible, can you please point me to how we fixed it in the main branch ?

**Comment by franz1981** [comment]
@mind-fuzzy https://github.com/netty/netty/blob/main/transport/src/main/java/io/netty5/channel/DefaultChannelPipeline.java#L78 It is using an array list (`synchronized`) which ids are stable (unless modified)

**Comment by olivergillespie** [comment]
Pinging @normanmaurer again just in case you missed it. You mentioned the issue is fixed but as franz1981 pointed out we don't actually seem to make use of the new `ArrayList handlers` in `findContextInbound`/`findContextOutbound`. So is that just something that hasn't been done, yet, but might be beneficial? I may try to implement it if I get time.

**Comment by normanmaurer** [comment]
With the changes @chrisvest did we can close this imho
