### ISSUE TITLE
HttpContentDecoder NPE

### ISSUE THREAD

**Issue by valodzka** [netty/netty#3317]
Upgraded to netty 25 and getting following exception sometimes:

        io.netty.handler.codec.DecoderException: java.lang.NullPointerException
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:241)
    at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:212)
    at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:132)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
    ...
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
        Caused by: java.lang.NullPointerException: null
    at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:86)
    at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:45)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
     ... 17 common frames omitted   
 
Versions:
    
    Netty 4.0.25.Final
    java 1.8.0_25

**Comment by normanmaurer** [comment]
You upgraded from which version?

**Comment by valodzka** [comment]
From 4.0.24.Final

**Comment by trustin** [comment]
```java
            if (!decodeStarted) {
                decodeStarted = true;
                HttpMessage message = this.message;
                HttpHeaders headers = message.headers();
                this.message = null;
```

`message` seems to be `null` for an unknown reason.  @valodzka, do you have a reliable way to reproduce this issue?

**Comment by trustin** [comment]
Putting the fix aside, we should raise `IllegalStateException` when `HttpContent` is received without `HttpMessage`.

**Comment by valodzka** [comment]
@trustin I don't have simple test case, but issue happens quite often on our servers, I can deploy some debug build in our staging servers if it will help.

**Comment by trustin** [comment]
I wonder if you can insert a `LoggingHandler` between `HttpServerCodec` (or `HttpRequestDecoder`) and `HttpContentDecoder` to see `HttpRequestDecoder` produces what message sequence when the NPE is raised.

**Comment by gariev** [comment]
should be fixed by https://github.com/netty/netty/pull/3329
however, the cause of NPE is unknown

**Comment by normanmaurer** [comment]
@valodzka could you verify it is fixed with latest 4.0 branch ?

**Comment by valodzka** [comment]
Tested with 4.0.26.Final-SNAPSHOT, issues still here.
It probably happens in case of slow reading/read timeout and some incomplete data processed.

    io.netty.handler.codec.DecoderException: java.lang.NullPointerException
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:314)
    at io.netty.channel.AbstractChannelHandlerContext.invokeNextChannelRead(AbstractChannelHandlerContext.java:322)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:300)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:314)
    at io.netty.channel.AbstractChannelHandlerContext.invokeNextChannelRead(AbstractChannelHandlerContext.java:322)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:300)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:288)
    at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:212)
    at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:132)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:214)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:200)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
     ...
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:214)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:200)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException: null
    at io.netty.handler.codec.http.HttpObjectAggregator.decode(HttpObjectAggregator.java:174)
    at io.netty.handler.codec.http.HttpObjectAggregator.decode(HttpObjectAggregator.java:54)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
     ... 22 common frames omitted

**Comment by valodzka** [comment]
I was able to reproduce bug locally, log is here: https://gist.github.com/valodzka/59a7594b4d69309bc241

**Comment by normanmaurer** [comment]
@valodzka can you still reproduce this with 4.0.33.Final ?

**Comment by valodzka** [comment]
Unfortunately I cannot test it thoroughly, issue #4679 blocks it deployment on our servers without significant modifications.

**Comment by Scottmitch** [comment]
@valodzka - https://github.com/netty/netty/issues/4679 is now fixed, can you test now?

**Comment by valodzka** [comment]
I tested snapshot build for a few hours and seems bug is fixed.

**Comment by normanmaurer** [comment]
@valodzka thanks!
