### ISSUE TITLE
EventloopGroup shutdownGracefully closes the connections right away.

### ISSUE THREAD

**Issue by fantayeneh** [netty/netty#3699]
Trying to implement a graceful shutdown of a netty server.  using version `4.0.21`
As described in the docs we are using 

```
 bossGroup.shutdownGracefully().await();
 workerGroup.shutdownGracefully().await();

```

This is actually shutting down all the connection in the worker group right a way.
Looking into the code it seems that in the `NioEventLoop` the following code seems incorrect

```
protected void run() {
        for (;;) {
...
                if (isShuttingDown()) {
                     closeAll();
                    if (confirmShutdown()) {
                        break;
                    }
                }
 ...
        }
    }
```

Making the `closeAll()` call only after the confirmShutdown call  did seem to work. (waits until the inflight requests finishes before closing the connections)
```    
if (isShuttingDown() && confirmShutdown()) {
	closeAll();
	break;
}
```
Which makes sense as it will shutdown only after the graceful timeout period.

**Comment by mikkokar** [comment]
At the same token, the documentation for `shutdownGracefully()` can be improved. If our understanding is correct, the intended behaviour is:

```
    /**
     * Signals this executor that the caller wants the executor to be shut down.  Once this method is called,
     * {@link #isShuttingDown()} starts to return {@code true}, and the executor prepares to shut itself down.
     *
     * Graceful shutdown ensures that the EventExecutorGroup is not shut down before <i>'quiet period'</i>
     * of inactivity. If a task is submitted during the quiet period, it is guaranteed to be accepted and the
     * quiet period will start over.
     *
     * @param quietPeriod the quiet period as described in the documentation
     * @param timeout     the maximum amount of time to wait until the executor is {@linkplain #shutdown()}
     *                    regardless if a task was submitted during the quiet period
     * @param unit        the unit of {@code quietPeriod} and {@code timeout}
     *
     * @return the {@link #terminationFuture()}
     */
```

Currently it says:

```
     * Unlike {@link #shutdown()}, graceful shutdown ensures that no tasks are submitted for <i>'the quiet period'</i>
     * (usually a couple seconds) before it shuts itself down.  If a task is submitted during the quiet period,
     * it is guaranteed to be accepted and the quiet period will start over.
     *
```

**Comment by normanmaurer** [comment]
@fantayeneh @mikkokar both sound good to me... @trustin WDYT ?

**Comment by normanmaurer** [comment]
I think this was fixed

**Comment by CheeriosJo** [comment]
Is this really fixed? According to [3706](https://github.com/netty/netty/pull/3706), this was closed as not a bug.  I am still seeing connections being close right away regardless of what quietPeriod and timeout is set to on 4.0.34-final.
