### ISSUE TITLE
DNS query ID space exhaustion

### ISSUE THREAD

**Issue by dmk23** [netty/netty#3972]
In running big DNS resolution loads with very high parallellism and logging turned on I'm running into query ID space exhaustion (logged messages below).

As I've reviewed the Netty DNS code, I see there is a hard limit of 65536 queries max (in reality a lot less because there would be too many collisions to obtain an ID even with less concurrency).

Wouldn't it make sense to replace the AtomicReferenceArray that holds the promises with a ConcurrentHashMap that could grow as large as necessary? It could also be keyed by the original DnsQuestion, making it *much* easier to troubleshoot the cases when the query fails and the original question gets lost somewhere. Note, even the current code seems to be doing something wrong, as I have also received warnings about DNS responses with an unknown ID (details below).

Perhaps the choice of the promise collection between AtomicReferenceArray vs. ConcurrentHashMap could be exposed as a configuration option to the user, if the original behavior is worth preserving 

```
2015-07-02 13:39:53,041 WARN  [epollEventLoopGroup-2-1] dns.DnsNameResolver: Received a DNS response with an unknown ID: 55787
```

```
2015-07-02 14:45:02,108 WARN  [epollEventLoopGroup-2-1] concurrent.DefaultPromise: An exception was thrown by com.test.XXXXXXXXXXXXXXXX
java.lang.IllegalStateException: query ID space exhausted: DefaultDnsQuestion(eske.net IN MX)
        at io.netty.resolver.dns.DnsQueryContext.allocateId(DnsQueryContext.java:92)
        at io.netty.resolver.dns.DnsQueryContext.<init>(DnsQueryContext.java:70)
        at io.netty.resolver.dns.DnsNameResolver.query0(DnsNameResolver.java:735)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:694)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:662)
...
2015-07-02 14:45:02,060 WARN  [epollEventLoopGroup-2-1] concurrent.DefaultPromise: An exception was thrown by com.test.XXXXXXXXXXXXXXXX
java.lang.IllegalStateException: query ID space exhausted: DefaultDnsQuestion(talkingrockcommunications.com IN MX)
        at io.netty.resolver.dns.DnsQueryContext.allocateId(DnsQueryContext.java:92)
        at io.netty.resolver.dns.DnsQueryContext.<init>(DnsQueryContext.java:70)
        at io.netty.resolver.dns.DnsNameResolver.query0(DnsNameResolver.java:735)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:694)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:662)
...
2015-07-02 14:45:01,529 WARN  [epollEventLoopGroup-2-1] concurrent.DefaultPromise: An exception was thrown by com.test.XXXXXXXXXXXXXXXX
java.lang.IllegalStateException: query ID space exhausted: DefaultDnsQuestion(mailin2.allsupinc.com IN A)
        at io.netty.resolver.dns.DnsQueryContext.allocateId(DnsQueryContext.java:92)
        at io.netty.resolver.dns.DnsQueryContext.<init>(DnsQueryContext.java:70)
        at io.netty.resolver.dns.DnsNameResolver.query0(DnsNameResolver.java:735)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:694)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:662)
```

**Comment by trustin** [comment]
I didn't expect people to produce such amount of load obviously. Let me get the query ID allocation done on per-server basis rather than on per-resolver basis.

**Comment by dmk23** [comment]
Thanks. If you want to keep an array structure, perhaps it could be a configurable setting? In either case it should be possible to get the originally submitted DnsQuestion in the listener.

**Comment by normanmaurer** [comment]
I think this was fixed by @trustin ... @trustin WDYT ?

**Comment by trustin** [comment]
Not fixed yet

--
https://twitter.com/trustin
https://twitter.com/trustin_ko
https://twitter.com/netty_project
 
 
On Wed, Sep 9, 2015, at 09:42 PM, Norman Maurer wrote:
> I think this was fixed by @trustin[1] ... @trustin[2] WDYT ?


> —
> Reply to this email directly or view it on GitHub[3]. 


>  
 


Links:

  1. https://github.com/trustin
  2. https://github.com/trustin
  3. https://github.com/netty/netty/issues/3972#issuecomment-138896842

**Comment by serphacker** [comment]
DNS txid space is limited to 0-65535, like @trustin suggested we can use a txid pool per server, but maybe we could do a txid pool per source port ?

I think a dns query identifier is `source port` + `transaction id` we can send the same transaction id to a same server, but using a different source port. This way we have a far bigger query id space.

**Comment by dmk23** [comment]
I'd support any solution that would extend the query ID space...

**Comment by trustin** [comment]
Busy at work - will fix when I have time. PR welcome.

**Comment by normanmaurer** [comment]
Fixed by #4455
