### ISSUE TITLE
Decryption failed or bad mac record in Android 5.0

### ISSUE THREAD

**Issue by grgvineet** [netty/netty#4116]
Netty version : from 4.0.26 onwards

Context : SSL client from Android device

While using SSL client in Android 5.0, an exception is thrown stating that decryption failed or bad mac record. The issue is only with Android 5.0 and not with any other version. It might be a bug in internal library of Android, but this exception is only encountered from Netty 4.0.26 onwards. For versions earlier than this, no exception is thrown and I can get a successful connection and can send data.
Here is the stack trace for device

08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: javax.net.ssl.SSLProtocolException: Read error: ssl=0xafa2cc00: Failure in SSL library, usually a protocol error
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac (external/openssl/ssl/s3_pkt.c:485 0xabde7ce0:0x00000000)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:346)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:229)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ Caused by: javax.net.ssl.SSLException: javax.net.ssl.SSLProtocolException: Read error: ssl=0xafa2cc00: Failure in SSL library, usually a protocol error
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac (external/openssl/ssl/s3_pkt.c:485 0xabde7ce0:0x00000000)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:491)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1114)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:981)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:934)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:315)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ ... 12 more
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0xafa2cc00: Failure in SSL library, usually a protocol error
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac (external/openssl/ssl/s3_pkt.c:485 0xabde7ce0:0x00000000)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at com.android.org.conscrypt.NativeCrypto.SSL_read_BIO(Native Method)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:472)
08-20 03:26:19.356    2633-2915/org.kde.nettytest W/System.err﹕ ... 17 more

Steps to reproduce : 
1. Use this app https://github.com/grgvineet/NettyTest
2. Run client on Android 5.0, error is thrown
3. Change netty version in build.gradle to 4.0.25
4. Try again, it will work
5. Reproducible always

**Comment by normanmaurer** [comment]
@grgvineet will check

**Comment by normanmaurer** [comment]
@grgvineet could you try to find out which specific commit is guilty here ? I have no android for testing.

**Comment by grgvineet** [comment]
@normanmaurer The commit causing issue is this "f46a3d74d0637aeb51326cceccfbee950d9e6838 Reduce memory copies when using OpenSslEngine with SslHandler". I will say it again, the issue is only in Android 5.0 and in only client mode but still it will be nice if it work in that too :) . Let me know if any further help is needed.

**Comment by normanmaurer** [comment]
@grgvineet thanks... Will check if I can find out what's wrong

**Comment by normanmaurer** [comment]
@grgvineet do you use the OpenSslEngine ?

**Comment by grgvineet** [comment]
@normanmaurer I used the default engine, but from Android 5.0 onwards, Android internally uses OpenSSL for security purposes

**Comment by m3ltaw4y** [comment]
Is there any solution to this?  I believe I have the same problem.  Described here: http://stackoverflow.com/questions/34214768/netty-4-decoder-error-with-ssl

**Comment by normanmaurer** [comment]
Unfortunaly I have no android to debug and test it :(

**Comment by slandelle** [comment]
Ask your employer for one!

**Comment by normanmaurer** [comment]
@slandelle I guess I'm working for the wrong company for an android device ;)

**Comment by m3ltaw4y** [comment]
The errors occur on Android emulators as well

**Comment by normanmaurer** [comment]
If you can give me some infos how to setup all of this I will have a look. I’m using intellij …

**Comment by m3ltaw4y** [comment]
I'm using Netty 4.0.30, problems occur with Android 5.02 on real devices and emulators, but not earlier versions.  I believe the sample code here will expose this: https://github.com/netty/netty/tree/4.0/example/src/main/java/io/netty/example/securechat  
I use Android Studio's emulator, haven't used intellij

**Comment by DaAllexx** [comment]
I can confirm this issue. It is not just Android 5.0.2, it is Android 5.0.X in general. With all Android versions before and after 5.0.X all SSL connections are working fine. For now we are using Netty 4.0.25 in our app as a workaround.

To reproduce this you just have to try to establish a SSL connection with Netty. In Android Studio you just have to create a virtual device using the AVD Manager. To run you simply press the "Run" button and Android Studio asks you whether you want to run it on a real device or on your virtual device.

**Comment by normanmaurer** [comment]
Will try sometime this week

**Comment by normanmaurer** [comment]
@DaAllexx can you somehow create a github project that I just can clone and only run to reproduce it ? I never used the android studio thing and I'm completely clueless. This would help me a lot.

**Comment by DaAllexx** [comment]
Here it is: https://github.com/DaAllexx/netty-android-example
Just run it on a Virtual Device (with API Level 21) and you will get the error, if you need any additional information just message me.

**Comment by normanmaurer** [comment]
@DaAllexx I only see:

```
01-05 21:54:28.093 9968-9995/de.tunebitfm.nettyexample I/websocket-client: Connected to the websocket service!
```
What error I should see ?

**Comment by normanmaurer** [comment]
@DaAllexx never mind used API version 22 by mistake. Thanks will take it from here :)

**Comment by normanmaurer** [comment]
@DaAllexx @grgvineet this workaround fixes it: #4678

**Comment by DaAllexx** [comment]
@normanmaurer Thank you!

**Comment by normanmaurer** [comment]
@DaAllexx let me know if it works

**Comment by grgvineet** [comment]
@normanmaurer Thanks! What is the expected date for release with this fix ?

**Comment by normanmaurer** [comment]
Next week

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty/pull/4678

**Comment by m3ltaw4y** [comment]
Unfortunately I still see the same issue in io.netty:netty-all:4.0.34.Final-SNAPSHOT and io.netty:netty-all:4.1.0.Beta8
Am I grabbing the wrong version or something?  io.netty:netty-all:4.0.25.Final still works fine.

**Comment by Scottmitch** [comment]
This issue still existing in `4.0.34.Final-SNAPSHOT` sounds problamtic but `4.1.0.Beta8` does not include #4678 so can you instead try `4.1.0.CR1-SNAPSHOT`?

@DaAllexx - Can you verify the issue still exists for you too?

@m3ltaw4y - Can you also provide a reproducer project like @DaAllexx? It would be nice if we could just run a unit test (the less non-netty stuff we have to figure out the more likely we are to find/fix the issue).

**Comment by m3ltaw4y** [comment]
Sorry if this is overly complicated to run, but it was simplest for me to make this:
https://github.com/m3ltaw4y/MyGdxGame
To get it to work:  
1. In MyGdxGame.java change the parameter for SSLServerThread to be an available port.
2. In MyGdxGame.java change the parameters for the SSLClientThread to your desktop IP and the same port.
3.  Run two copies of this, one as a desktop application, one as an android application.  
4.  If you are running a working version of android, 4.4.4 for example, you'll see a bunch of messages printing.  If you are running a bugged version of android, 5.0.2 for example, youll see a netty error on the android side.  
5.  You can also change the netty build in build.gradle (and comment out any server code) to try netty 4.0.25 and confirm that the netty errors are not present even with the bad android versions.

**Comment by normanmaurer** [comment]
I will take a look

**Comment by DaAllexx** [comment]
I just tried 4.0.34.Final-SNAPSHOT and it seems to be fixed for me. I only tested it on a Virtual Device, but I try to get a physical device with Android 5.0 (API 21) to test it there too.

**Comment by normanmaurer** [comment]
@DaAllexx thanks for the feedback. That was exactly what I did... just used android studio and tested it with all different version when I wrote the fix.

**Comment by m3ltaw4y** [comment]
I get the failing behavior on a real device (HTC One with Android 5.0.2) and on an emulator (Nexus 5 api 21 x86)
I get the passing behavior on a real device (Nexus 4 with android 4.4.4) and on an emulator (Nexus 5 api 19)

**Comment by grgvineet** [comment]
I downloaded 4.0.34.Final-SNAPSHOT from garage.netty.io/teamcity. It is working fine for me. Tested on a real device with Android 5.0.2.

**Comment by grgvineet** [comment]
I tested using one phone and openssl cli on my laptop. It worked fine, but for a connection between two phones its giving same error.

**Comment by normanmaurer** [comment]
So let me close this... If you still think there is an issue please reopen

**Comment by m3ltaw4y** [comment]
I am still having this problem.  I am currently using 4.0.25.Final as a work around it is the last working version.  This issue still exists in all tested versions up to and including 4.0.36.Final

**Comment by Scottmitch** [comment]
@m3ltaw4y - Please provide a reproducer and instructions on how to setup and run it. Assume we are not familiar with Android or Android simulators.

**Comment by m3ltaw4y** [comment]
I've added some more detail to my previous post, if you get stuck somewhere let me know what isn't working-
https://github.com/m3ltaw4y/MyGdxGame
To get it to work:

1. Download and install android studio
2. File-Open The folder of MyGdxGame
3. I've added a desktop executable.  Run desktop-1.0.jar You should just be able to double click it (or run it from a command line if you'd like to see the output)  It uses port 13769 which hopefully is available.
4. In MyGdxGame\core\src\com\mygdx\game\MyGdxGame.java change the arguments for the SSLClientThread to a String of your desktop IP and the same port.
5. In Android studio on the top bar you should see a play button next to the word android.  Click the play button run the game.  It should ask you to select a target device. 
6. Click create new emulator.  select nexus 5 (this choice shouldn't matter)
7. Select a system image, download the API needed.  Use API level 21 to cause the error.  Or use API level 19 to avoid the error.  Click next, then finish.  Select the newly created emulator to run the application.  
8.  After the emulator powers on and installs the application you should see output in the android monitor at the bottom of the android studio which will display the error.  If you have avoided the error, you will see a bunch of messages scrolling by instead that say "granted".

Notes:
*If you are running a working version of android, 4.4.4 for example, you'll see a bunch of messages printing. If you are running a bugged version of android, 5.0.2 for example, you'll see a netty error on the android side.
*You can also change the netty build in MyGdxGame\build.gradle (and comment out any non compiling server code) to try netty 4.0.25 and confirm that the netty errors are not present even with the bad android versions.

**Comment by Scottmitch** [comment]
@normanmaurer - mind taking a look?
