### ISSUE TITLE
High CPU usage with SO_LINGER and sudden connection close (4.0.26.Final+)

### ISSUE THREAD

**Issue by ashish-tyagi** [netty/netty#4449]
We are using Netty 4.0.29.Final in one of our services. We are seeing high CPU usage (~100%) in certain periods and almost negligible CPU usage in remaining periods. Though there is no change in request rate. The request rate itself is very small (less than 100 per second per box). The service mostly does an inmemory cache lookup. The CPU and memory graph is below:
![bad1](https://cloud.githubusercontent.com/assets/8695441/11002917/bbc125d0-84d5-11e5-8312-013e3d7ff5c4.png)

We found that what differentiated periods of high CPU usage and periods of low CPU usage,was the amount of objects created per second (Notice the zigzag during high CPU phase and a smooth line during low CPU). When we did memory profiling during the high CPU periods, we saw that more than 90% instances are of PoolThreadCache$MemoryReagionCache$Entry, DirectByteBuffer, Recycler$DefaultHandle and Integer. The screenshot is below:
![bad2](https://cloud.githubusercontent.com/assets/8695441/11002977/131f6af8-84d6-11e5-93f7-830036b0f32e.png)

When we tried Netty 4.0.33.Final in one of our boxes, we found that the DirectByteBuffer instances remained the same but the instances of PoolThreadCache$MemoryReagionCache$Entry dropped drastically (~600). This was possibly because of this PR: https://github.com/netty/netty/issues/4071

I scanned Netty commit logs to find all the changes that have went in for PoolThreadCache. There was one major PR (https://github.com/netty/netty/issues/2264), that went with Netty 4.0.18.Final.

We tried with the previous Netty version 4.0.17.Final with one of the production instances. There was hardly  any CPU usage for this instance. The graphs and memory profiler report are attached below. These were taken at the same time as the previous graphs, under exactly same load.
![good1](https://cloud.githubusercontent.com/assets/8695441/11003432/86022c3e-84d8-11e5-9bf6-a03e24800168.png)
![good2](https://cloud.githubusercontent.com/assets/8695441/11003431/85ca893c-84d8-11e5-8226-6323b8eddd5e.png)

**Comment by ninja-** [comment]
soo you have a lot of DirectByteBuffers and MemoryRegionCache entries, but no channel outbound buffer entries there? what exactly are you doing with these buffers? **what's your usecase like http proxy etc.**?
in general I would assume you are writing too fast to the channel skipping isWritable(), and maybe latest netty versions made that more visible. the reason why you have 500 mil instances is that they aren't recycled since it's above the recycler size limit, so an instance is created every time. when you aren't like writing too fast etc. it should be stable around 200k*cores*2 max without gc, so much much less.

**Comment by ashish-tyagi** [comment]
Thanks Ninja. Replies follow.

No this is not a HTTP proxy but a typical request/response model service. We are checking for channel active before writing. I don't think, it is related to that though, because the same should be producible with older Netty version also (may be not in form of too many objects but atleast in CPU usage).

**Comment by ashish-tyagi** [comment]
Accidently closed. Reopening.

**Comment by ninja-** [comment]
so verify this with leak profiler on paranoid first, because that's how it looks from the screenshot

**Comment by ashish-tyagi** [comment]
Just ran the leak detector with PARANOID level. Was expecting logs from class  io.netty.util.ResourceLeakDetector. However, no leak related logs found in 5 min. Though, I will redo the test with bigger period.
Btw had it been a memory leak, the buffer memory and the heap memory would have increased with time. However, we have found no such thing even when servers ran for 10 days straight.

**Comment by ninja-** [comment]
@ashish-tyagi could you check whether these "leaked" buffers have any references or are left with no references for gc?

**Comment by normanmaurer** [comment]
@ashish-tyagi can you try to adjust the cache sizes of the PooledByteBufAllocator ?

**Comment by ashish-tyagi** [comment]
@ninja- These buffers (DirectByteBuffer) get collected by GC within a second or two. During high CPU periods, the memory churn is really high. Millions of buffers get created and destroyed in couple of seconds. When we hit the low CPU periods, we can hardly notice presence of DirectByteBuffer objects. 

The high memory churn is evident in the screen shots attached. During high churn (high CPU also), the memory usage increases by 1-2 GB within a second and then it comes back down to same level, in next second. In contrast, during the low memory churn (low CPU), the memory increases by 2GB in 3 min (i.e 11 MB/sec). Nothing changes from incoming requests perspective.

**Comment by ashish-tyagi** [comment]
@normanmaurer We are using the default cache sizes. Can you please suggest test values for the  cache sizes?

**Comment by Scottmitch** [comment]
@ashish-tyagi - It depends on which size buffers you allocate the most. You can also use the [PoolArenaMetric exposed by PooledByteBufAllocator](https://github.com/netty/netty/blob/master/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L337) to get more insight.

**Comment by normanmaurer** [comment]
@ashish-tyagi ping

**Comment by ashish-tyagi** [comment]
Sorry guys, it is a lot of time without an update. This was holiday season in India. Will give you an update by tomorrow.

**Comment by ashish-tyagi** [comment]
I was able to produce the issue by replaying recorded traffic. Problem produces when I kill the client suddenly. The CPU usage shoots to ~100% and remains there for a long time even, when though there are no incoming requests. At this stage, the CPU profiling shows these results.
![image](https://cloud.githubusercontent.com/assets/8695441/11155887/6d958b8c-8a6e-11e5-9516-63b9c0f9ad83.png)

The memory profiling yields similar results as before.
![image](https://cloud.githubusercontent.com/assets/8695441/11156050/72c7e018-8a6f-11e5-9fb0-a5b2113563d4.png)

The connections are in ESTABLISHED state on server machine. But the client does not show any connection to the server in netstat output.

**Comment by ashish-tyagi** [comment]
Will try to produce in a standalone test case.

**Comment by normanmaurer** [comment]
Thanks!

**Comment by ninja-** [comment]
@ashish-tyagi yeah looks like there might be a bug involved, could you consider moving to epoll for now?

**Comment by normanmaurer** [comment]
I’m sure if there is a bug it has nothing to do with using epoll or not …

**Comment by ninja-** [comment]
well if there is it seems to come from nio backend at least

**Comment by ashish-tyagi** [comment]
Tried to figure out the exact version between 4.0.18.Final and 4.0.29.Final, where the problem started producing. It seems that it started producing with 4.0.26.Final (changing this issue title to reflect that). However, the behavior of 4.0.26.Final is different from 4.0.29.Final in that 4.0.26.Final is heavy on GC too, because of this issue: https://github.com/netty/netty/issues/3913, which got fixed here: https://github.com/netty/netty/commit/275e2f0b3689a2f560a4e6c70c1f8929ee16beb7#diff-cfab6ab9111be41b2f39beb8d154e79fR540

Adding CPU/memory usage and memory profile of versions 4.0.26.final to 4.0.28.Final.  
**4.0.26.Final**
![v26 1](https://cloud.githubusercontent.com/assets/8695441/11162759/76a302e6-8ad6-11e5-8303-acd0cb562d34.png)
![v26 2](https://cloud.githubusercontent.com/assets/8695441/11162760/76a66c10-8ad6-11e5-9628-becb48563d37.png)
  
**4.0.27.Final**
![v27 1](https://cloud.githubusercontent.com/assets/8695441/11162767/981bfbb2-8ad6-11e5-9f20-2ef7981f87df.png)
![v27 2](https://cloud.githubusercontent.com/assets/8695441/11162768/981da0b6-8ad6-11e5-8f96-86ed4642e18f.png)

**4.0.28.Final**
![v28 1](https://cloud.githubusercontent.com/assets/8695441/11162772/ce49f25c-8ad6-11e5-9ddd-b60ac6daa9e7.png)
![v28 2](https://cloud.githubusercontent.com/assets/8695441/11162773/ce4f0062-8ad6-11e5-8218-59f2b634e1f7.png)

**Comment by ashish-tyagi** [comment]
Produced the issue in a standalone test case.   

**Server Environment**
OS: Ubuntu 14.04 LTS
Java: Sun JRE 1.8.0_66

**Steps to produce**

1. Setup the server with the code give below.
2. From another physical box, hit the server using the apache-bechmarker. Hitting the server from same box does not produce it. `ab -c 50 -n 100000 -k http://<server-ip>:4000/`
3. Kill ab after 5-10 secs by pressing Ctrl-C. You should see sudden high CPU usage on the server.  

**Server code**
```java
import static io.netty.handler.codec.http.HttpHeaders.Names.CONNECTION;
import static io.netty.handler.codec.http.HttpHeaders.Names.CONTENT_LENGTH;
import static io.netty.handler.codec.http.HttpHeaders.Values.KEEP_ALIVE;

import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.SimpleChannelInboundHandler;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.http.DefaultFullHttpResponse;
import io.netty.handler.codec.http.FullHttpRequest;
import io.netty.handler.codec.http.FullHttpResponse;
import io.netty.handler.codec.http.HttpHeaders;
import io.netty.handler.codec.http.HttpObjectAggregator;
import io.netty.handler.codec.http.HttpResponseStatus;
import io.netty.handler.codec.http.HttpServerCodec;
import io.netty.handler.codec.http.HttpVersion;


public class TestServer {

    public static void main(String[] args) throws Exception {
        new TestServer(4000).start();
    }

    private final int port;
    private final int availableProcessors = Runtime.getRuntime().availableProcessors();

    public TestServer(int port) {
        this.port = port;
    }

    public void start() throws Exception {
        getServerBootstrap().bind(port).sync();
        System.out.printf("Netty Server started at port [%s]\n", port);
    }

    public ServerBootstrap getServerBootstrap() {
        ServerBootstrap bootstrap = new ServerBootstrap();
        final EventLoopGroup bossGroup = new NioEventLoopGroup(1);
        final EventLoopGroup workerGroup = new NioEventLoopGroup(availableProcessors);

        bootstrap.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class)
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    protected void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast(new HttpServerCodec());
                        ch.pipeline().addLast(new HttpObjectAggregator(1048576));
                        ch.pipeline().addLast(new EchoHandler());
                    }
                });

        bootstrap.childOption(ChannelOption.SO_LINGER, 1000);

        return bootstrap;
    }

    public static class EchoHandler extends SimpleChannelInboundHandler<FullHttpRequest> {

        @Override
        public void channelRead0(final ChannelHandlerContext ctx, FullHttpRequest req) throws Exception {
            if (ctx.channel().isActive()) {
                FullHttpResponse response = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK,
                        req.content().copy());
                HttpHeaders.setIntHeader(response, CONTENT_LENGTH, req.content().readableBytes());
                HttpHeaders.setHeader(response, CONNECTION, KEEP_ALIVE);
                ctx.channel().write(response);
                ctx.flush();
            }
        }
    }
}
```

**Comment by normanmaurer** [comment]
@ashish-tyagi will try to reproduce and fix... thanks! Did you also try using netty 4.0.33.Final ?

**Comment by normanmaurer** [comment]
@ashish-tyagi btw what is a little bit confusing is that in your original report you was talking about PoolThreadCache while in your reproducer you are using not the PooledByteBufAllocator. Is this by mistake or not ?

**Comment by ashish-tyagi** [comment]
Hi @normanmaurer, We use PooledByteBufAllocator.DEFAULT in production. The reproducer works both with or without PooledByteBufAllocator. I originally believed that there are too many instances getting created, and that is what is causing the CPU load. With this reproducer, I think the root cause lies somewhere else (may be a infinite loop).

Also, the issue produces only when SO_LINGER is set.

**Comment by ashish-tyagi** [comment]
@normanmaurer The issue of high CPU usage remain in 4.0.33.Final also. The memory profile is different though from 4.0.29.Final. I am changing the title again to put high CPU as the main issue,

**Comment by normanmaurer** [comment]
@ashish-tyagi thanks for the clarification.

**Comment by ashish-tyagi** [comment]
@normanmaurer Could you produce the issue? In case not, see if using a slow network helps. I observed that the reproducer does not work if the server and the client are on same LAN. I can produce the issue always, when my server and my client use a slow internet connection for transportation.

**Comment by normanmaurer** [comment]
@ashish-tyagi had no time yet :(

**Comment by normanmaurer** [comment]
@ashish-tyagi working on a fix. I think I may know what the problem is

**Comment by ashish-tyagi** [comment]
@normanmaurer 
This is good. Did the issue produce in your environment?

**Comment by normanmaurer** [comment]
@ashish-tyagi I think this should fix it: https://github.com/netty/netty/pull/4516 Could you confirm ?

**Comment by ashish-tyagi** [comment]
Hi @normanmaurer, Took your code changes, applied them to Netty 4.0.29.Final I still see a high CPU usage. The method is called but the catch block is not even called as no exception happens.

Will try with 4.0.33.Final.

**Comment by normanmaurer** [comment]
@ashish-tyagi hmm that is strange... can you do me the favour and just alter the code to always return `null` from the `closeExecutor()` block. I would be interested if this helps or not.

**Comment by normanmaurer** [comment]
@ashish-tyagi let me know once you were able to try the suggested change.

**Comment by ashish-tyagi** [comment]
@normanmaurer Sure would try this by tonight.

**Comment by ashish-tyagi** [comment]
@normanmaurer Yes returning null fixed the issue.

**Comment by normanmaurer** [comment]
Interesting... Will habe a look now

**Comment by normanmaurer** [comment]
@ashish-tyagi I now tried to reproduce it for 2 hours without any luck :( As you can reproduce it quite easily can you give me some more infos about the client that runs ab ? like what version, what os etc ?

**Comment by normanmaurer** [comment]
@ashish-tyagi are you talking about a "short spike" a.k.a 1 sec or a long time of high cpu usage ?

**Comment by ashish-tyagi** [comment]
Hi @normanmaurer, I looked at the code and it seemed that the CPU spike should remain for a time equal to the SO_LINGER. However, in my setup, I have seen that sometimes the CPU usage comes down in 3-4 seconds, but most of the times it stays high even after 15 minutes. There is no new traffic.

**Comment by ashish-tyagi** [comment]
Client details:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

As far as I know, all software are standard available, and there are no custom patches.

**Comment by normanmaurer** [comment]
@ashish-tyagi can you do me a last favour and alter NioSocketChannel.closeExecutor like this:

```java
@Override
        protected Executor closeExecutor() {
            try {
                if (javaChannel().isOpen() && config().getSoLinger() > 0) {
                    return ForkJoinPool.commonPool();
                }
            } catch (Throwable ignore) {
                // Ignore the error as the underlying channel may be closed in the meantime and so
                // getSoLinger() may produce an exception. In this case we just return null.
                // See https://github.com/netty/netty/issues/4449
            }
            return null;
        }
```

Would be interesting to know if this helps at all.

**Comment by ashish-tyagi** [comment]
Hi @normanmaurer, Tried the new code. It is still the same.

Btw you can ask me for testing a code as many times as you like. I really appreciate your effort for this issue in particular and for open source in general.

I can not share the environment where this issue produces easily, as that belong to corp network. I am trying to produce the issue in Google cloud. If that works I will share the machine instances with you.

**Comment by johnou** [comment]
@ashish-tyagi you could also try sampling CPU with VisualVM to confirm where the busy loop is.

**Comment by ashish-tyagi** [comment]
@johnou The CPU profile is already attached in the comment dating  Nov 14, 2015. The busy loop is NioEventLoop which keeps on reading the same key, which keeps on failing because of underlying connection being closed, which causes Netty to schedule a close() in an executor.

**Comment by ashish-tyagi** [comment]
The executor which issues a close() gets stuck. I see these stack traces. These are not recovering either. Ideally the close() should block max for 1 sec (=SO_LINGER).

```

"ForkJoinPool.commonPool-worker-0" #24 daemon prio=10 os_prio=0 tid=0x00007f2c14001000 nid=0x49b9 runnable [0x00007f2c6824d000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.preClose0(Native Method)
	at sun.nio.ch.SocketDispatcher.preClose(SocketDispatcher.java:59)
	at sun.nio.ch.SocketChannelImpl.implCloseSelectableChannel(SocketChannelImpl.java:838)
	- locked <0x00000006c6a0e218> (a java.lang.Object)
	at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
	- locked <0x00000006c6a0e298> (a java.lang.Object)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:237)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:613)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$3(AbstractChannel.java:611)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:569)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

   Locked ownable synchronizers:
	- None

"ForkJoinPool.commonPool-worker-1" #23 daemon prio=10 os_prio=0 tid=0x00007f2c1c0b6800 nid=0x49b8 runnable [0x00007f2c6834e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.preClose0(Native Method)
	at sun.nio.ch.SocketDispatcher.preClose(SocketDispatcher.java:59)
	at sun.nio.ch.SocketChannelImpl.implCloseSelectableChannel(SocketChannelImpl.java:838)
	- locked <0x00000006c6a101a0> (a java.lang.Object)
	at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
	- locked <0x00000006c6a10220> (a java.lang.Object)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:237)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:613)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$3(AbstractChannel.java:611)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:569)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

   Locked ownable synchronizers:
	- None

"ForkJoinPool.commonPool-worker-2" #22 daemon prio=10 os_prio=0 tid=0x00007f2c1c0b5000 nid=0x49b7 runnable [0x00007f2c7418b000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.preClose0(Native Method)
	at sun.nio.ch.SocketDispatcher.preClose(SocketDispatcher.java:59)
	at sun.nio.ch.SocketChannelImpl.implCloseSelectableChannel(SocketChannelImpl.java:838)
	- locked <0x00000006c6a0d1d0> (a java.lang.Object)
	at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
	- locked <0x00000006c6a0d250> (a java.lang.Object)
	at io.netty.channel.socket.nio.NioSocketChannel.doClose(NioSocketChannel.java:237)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:613)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$3(AbstractChannel.java:611)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:569)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

   Locked ownable synchronizers:
	- None
```

**Comment by ashish-tyagi** [comment]
I measure the time for which the threads were stuck in close(), it was equal to SO_LINGER. I was under the assumption that SO_LINGER is in milliseconds, turns out that it is in seconds.

**Comment by ashish-tyagi** [comment]
@normanmaurer The problem is that if the channel is not closed in IO thread, the IO thread goes in an infinite loop, issuing close() again and again.

You can easily produce this issue even without SO_LINGER. Just comment out the code in `close()` method of `AbstractChannel` class. Open a connection and close it from the client side. The IO thread will go in infinite loop. I have put the reproducer code along with the modified `AbstractChannel` class in this [git repo(https://github.com/ashish-tyagi/netty-issue). This reproducer works even when both client and server are on same machine.

**Comment by normanmaurer** [comment]
@ashish-tyagi thanks a lot for all the infos. I now know what is wrong and started working on a fix. Without all your help I would never found the issue!

**Comment by johnou** [comment]
@normanmaurer any chance the fix for this will make it into netty-4.0.34.Final?

**Comment by normanmaurer** [comment]
@ashish-tyagi @johnou was on vacation... here is the proper fix: https://github.com/netty/netty/pull/4548 :)

**Comment by ashish-tyagi** [comment]
Nice. I would test and verify.

**Comment by normanmaurer** [comment]
This was fixed

**Comment by liboLiao** [comment]
@ashish-tyagi Could I ask what is the monitoring tool in the picture?

**Comment by johnou** [comment]
@liboLiao VisualVM
