### ISSUE TITLE
OpenSSL provider does not work with TLSv1.1 and TLSv1.0

### ISSUE THREAD

**Issue by erimatnor** [netty/netty#4918]
Not sure this is an issue with Netty, but I have been struggling to get Netty's OpenSSL context to allow clients to connect with protocols other than TLSv1.2. Although TLSv1.2 works well for most clients, we need to support older clients that only support TLSv1.1 or TLSv1.0 (e.g., older Android versions). If I configure Netty with the JDK SSL provider, then the earlier TLS protocol versions are available but not when using OpenSSL. This is despite the fact that the SSLEngine reports these protocols as supported and the Netty code seems to set SSL.SSL_PROTOCOL_ALL when creating the SSLContext. I've set the cipher list according to Mozilla's recommended list for compatibility, so there should be compatible ciphers available. Am I missing something or is there a bug in the OpenSSL provider? I am using Netty 4.1.CR3 with netty-tcnative-boringssl-static.

**Comment by Scottmitch** [comment]
This should be fixed by https://github.com/netty/netty-tcnative/pull/119. Can you try with Fork15-SNAPSHOT and verify this resolves the issue?

**Comment by hakvroot** [comment]
I have encountered the same issue as @erimatnor, also with Netty 4.1.CR3 + netty-tcnative-boringssl-static (@ linux-x86_64). I can still reproduce the issue with Fork15-SNAPSHOT; connecting with a non TLSv1.2 protocol results in

    io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000103:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL

**Comment by Scottmitch** [comment]
@hakvroot - Did you also update Netty's tcnative dependency and rebuild Netty? Netty makes direct usage of public static variables from tcnative.

**Comment by hakvroot** [comment]
@Scottmitch Good call, I did not. After recompiling Netty with the latest tcnative snapshot I can happily announce it works like a charm. Thanks!

For the future - are there plans to prevent the constants from being inlined?

**Comment by Scottmitch** [comment]
@hakvroot - No plans ATM. Feel free to open an issue though.

@erimatnor - I will close this for now. If rebuilding does not resolve your issue please re-open.

**Comment by dimitarg** [comment]
For future reference, works out of the box with 4.1.0-CR5, is broken on CR4

**Comment by normanmaurer** [comment]
@dimitarg thanks for pinging... Yes this is fixed in CR5 and will also be in 4.0.36.Final
