### ISSUE TITLE
Instrumented Netty

### ISSUE THREAD

**Issue by andrewharmellaw** [netty/netty#4981]
We'd like to use Netty in our Apache Camel app, but we're using Jetty for now as it has a [Codahale-Metrics-instrumented version.](https://dropwizard.github.io/metrics/3.1.0/manual/jetty/).

I'm happy to contribute this code to the project, but wanted (before embarking on the task) to check there was an appetite for this, and to see if anyone could provide a list of the classes, and instrumentation in the Netty codebase which I should look at.

I'm assuming following the instrumented-Jetty method of providing alternative jar(s) named metrics-* would be attractive.

Kind regards, Andrew

**Comment by andrewharmellaw** [comment]
Apologies, I just saw this: https://github.com/netty/netty/issues/922  Does that mean this has been resolved and we're just missing the documentation?

**Comment by normanmaurer** [comment]
@andrewharmellaw no it was not resolved... We did not really come to an "agreement" on how and what to instrument.

**Comment by andrewharmellaw** [comment]
Thanks for your reply @normanmaurer . Is this something there is an appetite to pick up again?  As I said, I'd be willing to contribute this (though I'm not au-fait with the Netty architecture so would need a few pointers as to what to instrument and in what way.)

**Comment by normanmaurer** [comment]
@andrewharmellaw sorry for the late response but we would love to add some thing like instrumentation. @Scottmitch @nmittler @trustin agree ?

**Comment by Scottmitch** [comment]
@andrewharmellaw @normanmaurer - Yes sounds good to me ... I this it would be good to discuss overall approach / API before digging into the implementation for this one.

**Comment by andrewharmellaw** [comment]
Sounds great guys. I've not put a great deal of thought into this, but the idea was to echo what you get with the metrics-intstrumented netty.  Thats from a consumer perspective however - the internals will likely be wildly different.  Please let me know how I can help / contribute in this discussion.

**Comment by prayagupd** [comment]
And https://github.com/netty/netty/issues/6523 from Mar 2017, not JMX support yet?
