### ISSUE TITLE
Sonarqube failure on CI server

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6161]
### Expected behavior
CI server should be able to run sonarqube and post results for each PR.

### Actual behavior
https://garage.netty.io/teamcity/viewLog.html?buildId=14967&buildTypeId=pulls_netty&tab=buildLog#_focus=190197

```
[21:35:24][io.netty:netty-parent] [ERROR] SonarQube server [https://garage.netty.io/sonarqube] can not be reached
```

I get a 502 bad gateway when requesting this URL from my browser.

### Steps to reproduce
Seen during 2 builds of PR https://github.com/netty/netty/pull/6155

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
4.1.7.SNAPSHOT PR build.

### JVM version (e.g. `java -version`)
jdk1.8.0_112 64 bit

### OS version (e.g. `uname -a`)
centos6-1 build slave

**Comment by normanmaurer** [comment]
Let me check

**Comment by normanmaurer** [comment]
should be fixed... service died.

**Comment by Scottmitch** [comment]
Thanks @normanmaurer !

**Comment by Scottmitch** [comment]
@normanmaurer - CI servers are still having issues with sonarqube.

PR
https://github.com/netty/netty/pull/6160

Build Slave
debian7-1

Build Log
https://garage.netty.io/teamcity/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=14996#_focus=195434

```
[20:50:10][Step 2/2] [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project netty-parent: Unable to execute SonarQube: Fail to download libraries from server: Status returned by url [https://garage.netty.io/sonarqube/batch_bootstrap/index] is not valid: [502] -> [Help 1]
[20:50:10][Step 2/2] [ERROR] 
[20:50:10][Step 2/2] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[20:50:10][Step 2/2] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[20:50:10][Step 2/2] [ERROR] 
[20:50:10][Step 2/2] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[20:50:10][Step 2/2] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[20:50:10][Step 2/2] Process exited with code 1
[20:50:10][Step 2/2] Publishing artifacts
[20:50:10][Publishing artifacts] Collecting files to publish: [/var/lib/teamcity-agent/temp/buildTmp/.tc-maven-bi/maven-build-info.1.xml.gz => .teamcity]
[20:50:10][Publishing artifacts] Publishing 1 file [/var/lib/teamcity-agent/temp/buildTmp/.tc-maven-bi/maven-build-info.1.xml.gz => .teamcity] using [ArtifactsCachePublisher]
[20:50:10][Publishing artifacts] Publishing 1 file [/var/lib/teamcity-agent/temp/buildTmp/.tc-maven-bi/maven-build-info.1.xml.gz => .teamcity] using [WebPublisher]
```

**Comment by normanmaurer** [comment]
Will Check tomorrow

**Comment by Scottmitch** [comment]
Another failure during CI build

PR
https://github.com/netty/netty/pull/6171

Build Slave
pulls-1

Build Log
https://garage.netty.io/teamcity/viewLog.html?buildId=15058&buildTypeId=pulls_netty&tab=buildLog#_focus=36

**Comment by normanmaurer** [comment]
sonaqube died because of OOME ... Increased the max heap space. let us see if this is good enough

**Comment by normanmaurer** [comment]
Fixed...
