### ISSUE TITLE
JsonObjectDecoder incorrect CorruptedFrameException?

### ISSUE THREAD

**Issue by mmcguill** [netty/netty#6208]
I have come across some strange behaviour while using the JsonObjectDecoder class. It is very intermittent but I managed to reproduce and provide a unit test below to demonstrate the issue. It appears from some initial investigation that the problem lies with the use of different ByteBufs, but I'll leave that for your analysis. Perhaps I'm not using the class correctly?

The 2 below JSON Strings are the minimal strings I could reproduce the issue with:

```
{
   "a":{
      "b":{
         "c":{
            "d":"27301",
            "med":"d",
            "path":"27310"
         }
      },
      "status":"OK"
   }
}
```
and the partial:
```
{
   "a":{
      "b":{
         "c":{
            "ory":[
               {
                  "competi":[
                     {
                        "event":[
                           {
                              "externalI":{
                                 "external":[
                                    {
                                       "id":"O"
                                    }
                                 ]

```

### Expected behavior
The JSON strings (one complete, one partial) are submitted to the JsonObjectDecoder split across 2 separate writes. I believe it should not throw a corrupt frame exception, it should produce one JSON string as output and remain read for further data, to arrive to complete the second JSON string, etc.

### Actual behavior
The code throws a CorruptedFrameException as indicated by the stacktrace below:
```
io.netty.handler.codec.CorruptedFrameException: invalid JSON received at byte position 82: 5d

	at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:163)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274) 
```
### Steps to reproduce
Please use the Unit Test provided below.

### Minimal yet complete reproducer code (or URL to code)

```
@Test
public void testCorruptedFrameException() {
    final String part1 = "{\"a\":{\"b\":{\"c\":{ \"d\":\"27301\", \"med\":\"d\", \"path\":\"27310\"} }, \"status\":\"OK\" } }{\"";
    final String part2 = "a\":{\"b\":{\"c\":{\"ory\":[{\"competi\":[{\"event\":[{" + "\"externalI\":{\"external\":[{\"id\":\"O\"} ]";
    
    EmbeddedChannel ch = new EmbeddedChannel(new JsonObjectDecoder());

    ch.writeInbound(Unpooled.copiedBuffer(part1, CharsetUtil.UTF_8));
    ch.readInbound();

    ch.writeInbound(Unpooled.copiedBuffer(part2, CharsetUtil.UTF_8));
    ch.readInbound();
}
```
### Netty version
4.1.6.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

### OS version (e.g. `uname -a`)
Darwin <hostname> 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
maybe related to https://github.com/netty/netty/pull/6157 ?

**Comment by andrewmccall** [comment]
I think you're right - I've added this test to my PR because this seems to fix it and is far simpler than the tests I was trying to write.

**Comment by mmcguill** [comment]
This is a possible fix. I'm not sure if it will introduce other issues, I've built my own decoder in the meantime, which resolved the issues I was seeing. Thanks!

**Comment by Scottmitch** [comment]
> I've built my own decoder in the meantime

😢. I'm glad things are working for you now ... but if you are able to contribute back that would be much appreciated.

**Comment by mmcguill** [comment]
@Scottmitch Unfortunately it's not quite as general a solution as you guys have here. For example I know I won't receive top/root level arrays, so I don't need to worry about that. I also don't need to consider "streaming" array items. It also doesn't place limits on input size. I've posted my version below, but I think it will be of limited use for your more general requirements. Perhaps it's useful to illustrate a slightly different approach. 

Hope that helps,
-Mark

```
import java.util.List;

import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelHandlerContext;
import io.netty.handler.codec.ByteToMessageDecoder;

public class JsonObjectDecoder extends ByteToMessageDecoder {
    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
        boolean foundJsonObject;
        
        do {
            foundJsonObject = false;
            SingleJsonObjectFsm decoder = new SingleJsonObjectFsm();

            for (int i = 0; i < in.readableBytes(); i++) {
                final byte c = in.getByte(in.readerIndex() + i);

                if (decoder.addCharacter(c)) {
                    ByteBuf frame = in.retainedSlice(in.readerIndex(), i + 1);
                    in.readerIndex(in.readerIndex() + i + 1);
                    out.add(frame);
                    foundJsonObject = true;
                    break;
                }
            }
        } while (foundJsonObject);
    }
}
```

which uses SingleJsonObjectFsm:

```
public class SingleJsonObjectFsm {
    private static final int ST_INIT = 0;
    private static final int ST_DECODING_NORMAL = 1;
    private static final int ST_DECODING_STRING = 2;
    private static final int ST_DONE = 3;

    private int state = ST_INIT;
    private int openBraces = 0;
    private boolean backslashEscapeActive = false;

    public boolean addCharacter(byte c) {
        if (state == ST_DONE) {
            throw new IllegalStateException();
        }
        else if (state == ST_INIT && (c == '{')) {
            state = ST_DECODING_NORMAL;
            openBraces++;
        }
        else if (state == ST_DECODING_STRING) {
            if (c == '\\' && !backslashEscapeActive) {
                backslashEscapeActive = true;
            }
            else if (c == '"' && !backslashEscapeActive) {
                state = ST_DECODING_NORMAL;
                backslashEscapeActive = false;
            }
            else {
                backslashEscapeActive = false;
            }
        }
        else if (state == ST_DECODING_NORMAL) {
            if (c == '"') {
                state = ST_DECODING_STRING;
            }
            else {
                if (c == '{') {
                    openBraces++;
                }
                else if (c == '}') {
                    openBraces--;
                }

                if (openBraces == 0) {
                    state = ST_DONE;
                    return true;
                }
            }
        }

        return false;
    }
}

```

**Comment by Scottmitch** [comment]
@mmcguill - Thanks for sharing, but as you indicated I don't think a less general solution will help most folks. I was hoping we could work toward fixing the more general solution (assuming this is the only issue preventing your use of it).

**Comment by mmcguill** [comment]
@Scottmitch I believe the fix from #6157 should do the trick.

**Comment by normanmaurer** [comment]
ok closing this now as fixed by #6157

**Comment by cdongtao** [comment]
hello, I still facing the same issue with using latest version io.netty:4.1.82: io.netty.handler.codec.CorruptedFrameException: invalid JSON received at byte position 523: 00,.Could you help for this and how can I fix this problem?
