### ISSUE TITLE
CorruptedFrameException when streaming Json array over multiple writes

### ISSUE THREAD

**Issue by violetagg** [netty/netty#6969]
### Expected behavior
One should be able to stream Json array over multiple writes

### Actual behavior
The exception is thrown
```
io.netty.handler.codec.CorruptedFrameException: invalid JSON received at byte position 43: 5d202020202020
	at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:170)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274)
	at io.netty.handler.codec.json.JsonObjectDecoderTest.testStreamJsonArrayOverMultipleWrites(JsonObjectDecoderTest.java:89)
```

### Steps to reproduce
The test case linked to this issue reproduces the exception above.
This commit https://github.com/netty/netty/commit/231e6a5b7d92a7455b5c64f8e4a71a6fcc73cfd1 is the cause for the problem.
If I comment the `reset` invocation the scenario is working again.
https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/json/JsonObjectDecoder.java#L95

### Minimal yet complete reproducer code (or URL to code)
See test case linked to this issue

### Netty version
Latest snapshot

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)
Darwin MacBook-Pro-2.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by Scottmitch** [comment]
Are you interested in submitting a PR to fix this issue?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6970

**Comment by cdongtao** [comment]
hello, I still facing the issue with using latest version io.netty:4.1.82: io.netty.handler.codec.CorruptedFrameException: invalid JSON received at byte position 523: 00
