### ISSUE TITLE
Netty Epoll.isAvailable() check doesn't handle lib loading issue on 32bit JVM

### ISSUE THREAD

**Issue by michaelandrepearce** [netty/netty#7150]
### Expected behavior
Method should check os and jvm variables if it can safely load the libs expected and return false and not cause JVM warning by loading incompatible libs

https://issues.apache.org/jira/browse/ARTEMIS-1099

### Actual behavior
using a 32 bit JVM:
Java HotSpot(TM) Server VM warning: You have loaded library /tmp/libnetty-transport-native-epoll7550636318037030956.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

### Steps to reproduce
Run netty native epoll on 32bit jvm 

### Minimal yet complete reproducer code (or URL to code)
see:
https://issues.apache.org/jira/browse/ARTEMIS-1099

### Netty version
4.1.x - present

### JVM version (e.g. `java -version`)
32bit any
### OS version (e.g. `uname -a`)
linux

**Comment by michaelandrepearce** [comment]
This seems similar to (possible duplicate ) https://github.com/netty/netty/issues/7120

**Comment by johnou** [comment]
@michaelandrepearce are you packaging your own epoll artifact? There is currently no 32 bit support for epoll. Iirc detecting actual architecture from jvm is not straightforward.

**Comment by michaelandrepearce** [comment]
@johnou No we're not, the isAvailable() check needs to take this into account though in its checks to detect if it is available, before trying to load the native libs.

**Comment by johnou** [comment]
@michaelandrepearce but I am running a custom packaged epoll artifact which runs on 32 bit architecture so the suggested changes will break our application :(

**Comment by Scottmitch** [comment]
@michaelandrepearce - can you describe the implication of the "Actual Behavior"? I would like to understand what the impacts of this issue are. For example is one of the following happening:
- Is it that the library is loaded and later crashes or does something unexpected?
- Does the load fail, and the error message is printed out, and you just don't want to see the error message?

**Comment by michaelandrepearce** [comment]
@scottmitch 
It loads the lib but due to the bit complied on invocation (used by is available) it causes a native stack error and then the jvm has to unload i gracefully. It does continue, but this reliance that the jvm can catch this safely unload really should be avoided.

**Comment by michaelandrepearce** [comment]
Re 32 bit custom builds, I think personally what is delivered in tested distributed build is what should be checked, if you have a custom build then you can custom update the check also.

Once/if netty provides a bundled/distributed 32 bit build then this would change but to deliver that a better native lib foldering and loading should be done like JNR project does with jffi.
Eg right now if a 32 bit and 64bit existed the netty all distro would overlay the two files as they would share the same fqn currrntly:

**Comment by Scottmitch** [comment]
I would prefer to avoid getting into the "filtering what we support game" and instead rely upon the linker/architecture to detect these issues. Is there an option to modify the link/build commands to fail in a manner that is cleaner, or some other approach to improve detection?

**Comment by michaelandrepearce** [comment]
As noted JNR uses a nice foldering structure and loading mechanism to support multiple bit builds and is specific builds. Maybe this could be adopted instead

**Comment by michaelandrepearce** [comment]
I note there is some override in the current hawtjni plugin that means it drops the platform folder, any specific reason? I ask as this is similar way that JNR does this, and if used would help this issue.

**Comment by johnou** [comment]
One could also argue it's a deployment issue (incorrect jar on the classpath), the classifier for the jar is  linux-x86_64..

**Comment by michaelandrepearce** [comment]
As noted dependency is on netty all (contains epoll and kqueue), and surely this is the point of the isAvailable check so code can see if it can safely use and then if not failback, aka back onto nio.

**Comment by michaelandrepearce** [comment]
Back to resolving this, is there any particular reason why overriding the default hawtjni and not use its loader?

**Comment by normanmaurer** [comment]
Fixed by #7163

**Comment by doom369** [comment]
@normanmaurer issue is still there with latest netty version.

**Comment by normanmaurer** [comment]
@doom369 thats super strange as the lib itself should have _x86_64 in its name which should only be true on a 64 bit architecture. Can you please check ?

**Comment by doom369** [comment]
@normanmaurer in jar I see 

```
libnetty_tcnative.so
libnetty_transport_native_epoll_x86_64.so
```

**Comment by normanmaurer** [comment]
in which jar ?

**Comment by normanmaurer** [comment]
ah ok.. this is for tcnative... We may need to have a fix in tcnative as well as this was fixed for the native transport of netty only imho

**Comment by doom369** [comment]
I suppose it comes from 

```
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>${netty.boring.ssl.version}</version>
            <classifier>${epoll.os}</classifier>
        </dependency>
```
Am I rgiht?

**Comment by doom369** [comment]
Will you reopen this ticket or should I create the corresponding issue for tcnative repo?

**Comment by normanmaurer** [comment]
please open one for tcnative 👍
