### ISSUE TITLE
Illegal reflective access warnings when running Netty with Java 9

### ISSUE THREAD

**Issue by doom369** [netty/netty#7254]
### Expected behavior

No warnings.

### Actual behavior

Warnings when starting netty with java 9:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/doom369/.m2/repository/io/netty/netty-common/4.1.16.Final/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

with `--illegal-access=warn` enabled :

```
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/doom369/.m2/repository/io/netty/netty-common/4.1.16.Final/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/doom369/.m2/repository/io/netty/netty-common/4.1.16.Final/netty-common-4.1.16.Final.jar) to method java.nio.Bits.unaligned()
```

### Steps to reproduce

Run any netty server with Java 9.

### Netty version

4.1.16.Final

### JVM version (e.g. `java -version`)

```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

Maybe it would be better to do not access above classes in case of java 9 to avoid warning?

**Comment by rockwotj** [comment]
Can we re-open this to actually solve the issue, I'd hate for things to break later on because this never got fixed?

The warning is quite clear this will break later on.

**Comment by doom369** [comment]
@rockwotj Actually when reflection access will be removed from Java 9 - netty will be ready. As fixed was already applied.

Netty was tested on EA builds were reflective access was removed and right now netty handles this case.

**Comment by rockwotj** [comment]
I see what version of netty has these changes?

**Comment by doom369** [comment]
It was many months ago - https://github.com/netty/netty/issues/6345

**Comment by alsnkline** [comment]
This seems strange to be open and closed at that same time.
I'm getting these errors also and would love to know when/how to upgrade Netty to get rid of them.

**Comment by normanmaurer** [comment]
I think we could add a system property that tells netty to not even try to access this stuff when running on java9. Let me reopen

**Comment by slachiewicz** [comment]
same problem with netty 4.1.13

**Comment by halber** [comment]
Still appears with netty 4.1.15.Final

**Comment by normanmaurer** [comment]
Yep... That said while a warning is logged netty works.

**Comment by normanmaurer** [comment]
I think we should just not try to use reflection when using java9 for now as this scares people and there is not much we can do anyway.

**Comment by normanmaurer** [comment]
@doom369 https://github.com/netty/netty/pull/7650 PTAL

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7650

**Comment by dynawink** [comment]
The error still occurs with netty 5.0.0.Alpha2. Please reopen the issue.

**Comment by rschoultz-wl** [comment]
> The error still occurs with netty 5.0.0.Alpha2. Please reopen the issue.

Did not get warning in 4.1.43.Final.

5.0.0.Alpha2 is from 2015.  Anything from 4.0.56.Final should be fine.

**Comment by nazar-art** [comment]
use spring boot project - 2.4.3
it takes netty-all version - 4.1.59.Final
and this warning also appears

**Comment by chrisvest** [comment]
@nazar-art Can you include the actual warning you see? Also, what Java version do you use?

**Comment by nazar-art** [comment]
@chrisvest Solve this issue by adding VM parameter: --illegal-access=warn
Tried to eliminate it. Don't see this warning anymore.

**Comment by johanneshiry** [comment]
Second that this issue occurs with following setup:

```netty jar 4.1.53 
java 14.02

args:
--add-opens java.base/jdk.internal.misc=ALL-UNNAMED 
-Dio.netty.tryReflectionSetAccessible=true 
--illegal-access=warn

warning:
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/<filepath-to-user>/gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.1.53.Final/f5aac2cd268483ded1f76dacc5c9eb27899dee72/netty-common-4.1.53.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
```

**Comment by chrisvest** [comment]
@johanneshiry You are seeing the warning because you have `-Dio.netty.tryReflectionSetAccessible=true` which overrides the default, which is `false` for Java 9 and above.

**Comment by YuriyGavrilov** [comment]
@normanmaurer 
Just got this warning with arrow jdbc driver installed in Tableau

`WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-10-12T22:09:48.924283 Protocol Server starting. 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cfjd.io.netty.util.internal.ReflectionUtil (file:/Users/yuriygavrilov/Library/Tableau/Drivers/flight-sql-jdbc-driver-10.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of cfjd.io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

**Comment by chrisvest** [comment]
@YuriyGavrilov  look into the system properties that tableu sets, and what netty version the jdbc driver shades. Then review the solutions already mentioned in this issue.

**Comment by wildbill51** [comment]
I had same issue but fixed this issue using jdk1.8.1x version instead of anything higher gives problems building basic test classes not associated with any db yet. But now all works as expected to not find any data until db is setup or H2.
