### ISSUE TITLE
Netty crashes when used by google cloud's logback

### ISSUE THREAD

**Issue by tsbonev** [netty/netty#8337]
### Expected behavior
Logback to call netty and make a connection with a google service account in order to send a log.

### Actual behavior
JRE crashes.

### Steps to reproduce
Create a google ServiceAccountCredentials

### Minimal yet complete reproducer code (or URL to code)
https://gist.github.com/tsbonev/1b2dcd1023e0178b9e995b0533d202a4

error:
https://gist.github.com/tsbonev/39de9ad8d786a307fcac35fbe1ab11b0

### Netty version
grpc-netty-shaded 1.15.0

### JVM version (e.g. `java -version`)
1.8.0_181

### OS version (e.g. `uname -a`)
16.04.1-Ubuntu

**Comment by normanmaurer** [comment]
Please show the crash dump / stacktrace

**Comment by tsbonev** [comment]
Crash stacktrace:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe477a014c0, pid=3581, tid=0x00007fe4aee96700
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00007fe477a014c0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/tsvetozar/clouway/workspaces/idea/pos-print/pos-print/hs_err_pid3581.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by tsbonev** [comment]
I've provided the hs_err log in the gist link after "error:"

**Comment by normanmaurer** [comment]
Looks like a shading issue to me... @ejona86 can you check?

**Comment by tsbonev** [comment]
Tracking it down with the debugger leads to a check in a class named Library, package io.grpc.netty.shaded.io.netty.internal.tcnative.

There's an if check in the initialize() method that uses aprMajorVersion() and it cannot get past that without crashing.

**Comment by steveniemitz** [comment]
I've run into this as well, interestingly enough I can only reproduce it in google dataflow (which sadly makes this way harder to debug), not on my own servers (or locally).  I initially thought it might be the JVM version, but I've tried it on 1.8.0_181 locally as well and couldn't reproduce the crash.

I'm using gRPC 1.13.2 (not shaded!), netty 4.1.28, and tcnative 2.0.12.  As far as I can tell nothing is using a shaded version of gRPC or netty anywhere

**Comment by normanmaurer** [comment]
@steveniemitz can you share your dependency graph and the core dump ?

**Comment by steveniemitz** [comment]
hmm, I can get you the log, the core dump might be trickier since there'll be some proprietary stuff in there.  Lemme see if I can craft up a repro case that has less "stuff" in it.  

Also I opened a case with Beam, I'm trying to figure out which version of tcnative they're bundling with their dataflow image.

My current theory looks something like this:
- We load the 2.0.12 tcnative jar from our classpath.
- It tries to load the native lib, but because of dataflow craziness, it loads a different version (which version I'm not sure)
- Apparently something between 2.0.10 and later versions breaks pretty catastrophically.

My guess is the original report above has a similar issue.

**Comment by ejona86** [comment]
This looks similar to https://github.com/netty/netty/issues/7272. It seems fixed in tcnative 2.0.14+.

The logback issue seems to be because logback is bringing in grpc as well. `io.grpc` is excluded for logging, but not logback. Logback brings in logging (again) which eventually brings in grpc 1.13.1 (grpc-netty _and_ grpc-netty-shaded) and netty-tcnative-boringssl-static 2.0.7.Final. So this is probably grpc-netty-shaded 1.15.0 (which has tcnative 2.0.12) fighting with netty-tcnative-boringssl-static 2.0.7.

Something similar is likely happening with Beam, although I really don't know much about it. I've crossed paths with Luke Cwik before; I may ask him to explain how Beam/Dataflow is built and confirm suspicions.

grpc-java 1.16.0 is due early next week, which will bump us to tcnative 2.0.17.

(In the back of my mind I'm not also worried what would happen if you have two same-named, different versions tcnatives separated by a ClassLoader. It seems that would break. We may need Conscrypt...)

**Comment by khodayar** [comment]
> This looks similar to #7272. It seems fixed in tcnative 2.0.14+.
> 
> The logback issue seems to be because logback is bringing in grpc as well. `io.grpc` is excluded for logging, but not logback. Logback brings in logging (again) which eventually brings in grpc 1.13.1 (grpc-netty _and_ grpc-netty-shaded) and netty-tcnative-boringssl-static 2.0.7.Final. So this is probably grpc-netty-shaded 1.15.0 (which has tcnative 2.0.12) fighting with netty-tcnative-boringssl-static 2.0.7.
> 
> Something similar is likely happening with Beam, although I really don't know much about it. I've crossed paths with Luke Cwik before; I may ask him to explain how Beam/Dataflow is built and confirm suspicions.
> 
> grpc-java 1.16.0 is due early next week, which will bump us to tcnative 2.0.17.
> 
> (In the back of my mind I'm also worried what would happen if you have two same-named, different versions tcnatives separated by a ClassLoader. It seems that would break. We may need Conscrypt...)
I have the same problem, grpc-java 1.16.0 didn't solve the issue

**Comment by marcosfilho** [comment]
I have the same issue running grpc-java 1.18.0

**Comment by normanmaurer** [comment]
Seems like this was fixed by a newer version. See https://github.com/googleapis/google-cloud-java/issues/3455. Closing it
