### ISSUE TITLE
Selector.select() returned prematurely 512 times in a row

### ISSUE THREAD

**Issue by mikomarrache** [netty/netty#8698]
I'm using Netty 4.1.32 and I see the following very very often in the logs:

```
2018-12-30 10:06:53.286  WARN 22878 --- [nioEventLoopGroup-2-7] io.netty.channel.nio.NioEventLoop        : Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@280b6859.
2018-12-30 10:06:53.287  INFO 22878 --- [nioEventLoopGroup-2-7] io.netty.channel.nio.NioEventLoop        : Migrated 20 channel(s) to the new Selector.
```

I assume I'm doing something wrong since it's logged as a warning.

My app is running on CentOS 7.

**Comment by mikomarrache** [comment]
I made 2 changes that solved the issues:

1. I release the `ReferenceCounted` (in my case, a `DatagramPacket`) as early as possible. This is clear to me that it has an impact on the direct memory used at any point of time.

2. I have a single `Channel` receiving `DatagramPackets`. The pipeline of this `Channel `consists of a single handler that dispatches processing of every `DatagramPacket` to an `ExecutorService`. The processing of a `DatagramPacket` involved an IO operation that was performed synchronously from this thread. I moved this operation to be executed later on a different `ExecutorService`.

First, I made the changes for point 1 and it didn't solve the issue (though I understand that it should help.

Then, I made the changes for the point 2 and the issues doesn't appear anymore.

I'm not sure why 2 solves the issue since my event loop single thread simply dispatches the packets (and submission is never rejected).

**Comment by mikomarrache** [comment]
After running a few days, I got the `OutOfDirectMemoryError` again but not the selector's issue.

I suspected the possibility that I'm writing too fast and indeed, using `Channel.isWritable()`, I see that the channels are very very often in a non-writable state.

What can be the cause?

**Comment by mikomarrache** [comment]
@normanmaurer 

I'm seeing this behavior some time (a few hours, maybe more - I'm investigating) after the application is started.

I'm sure it's not related to the flush since I only call `writeAndFlush`.

I also strongly doubt that the remote peer doesn't read fast enough since, after establishing the connection and a few initialization messages, I only send small ping messages every 30 seconds.

Therefore, I'm trying to understand what you are saying about the `EventLoop`. My bootstrap is configured as follows:

```
bootstrap = new Bootstrap()
	.group(new EpollEventLoopGroup())
	.channel(EpollSocketChannel.class)
	.option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
	.handler(/* My handler */);
```

I'm using the default `EventLoopGroup` constructor, so it creates threads based on the number of cores.

**Comment by mikomarrache** [comment]
@normanmaurer 

FYI, I'm not using the `Bootstrap.connect()` method as usual but I do the following:

```
final ChannelFuture registerFuture = bootstrap.register().syncUninterruptibly();
final Channel channel = registerFuture.channel();

/* Keep a reference of the channel somewhere */

channel.connect(/* Socket address */)
	.addListener((ChannelFuture future) -> {
		        if (!future.isSuccess()) {
			            future.channel().eventLoop().schedule(() -> {
			                doConnect(chromecast);
			            }, 30, TimeUnit.SECONDS);
		                    return; 
                       }
		        
		       channel.closeFuture().addListener((ChannelFuture _f) -> {
				doConnect(chromecast);
			});
	});
```

I don't think that's related but just in case...

**Comment by mikomarrache** [comment]
I have multiple environments that have exactly the same application. The only difference is the number of `Channel`s created by the application (and therefore the number of read/write operations handled by the `EventLoop`). The problematic environment is the one with 200 `Channel`s while the other environments manage not more than 60 `Channel`s. Therefore, I'm tend to think the issue is related to the `EventLoop` not being able to manage such number of operations. However, I'm very surprised that 200 TCP connections (with TLS) is the upper bound here.

Is there an easy way to check that it is really the issue? And if that's really the issue, what can be done to solve it?

**Comment by xzzh999** [comment]
@normanmaurer 
I have the same problem, just keep logging and CPU comes too high:
```
2019-02-27 13:50:31.007 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@eb3195b.
2019-02-27 13:50:31.009 INFO  io.netty.channel.nio.NioEventLoop - Migrated 1 channel(s) to the new Selector.
2019-02-27 13:50:36.013 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@62cac379.
2019-02-27 13:50:36.013 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@26c6900e.
2019-02-27 13:50:36.013 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@6b07426c.
2019-02-27 13:50:36.015 INFO  io.netty.channel.nio.NioEventLoop - Migrated 2 channel(s) to the new Selector.
2019-02-27 13:50:36.015 INFO  io.netty.channel.nio.NioEventLoop - Migrated 0 channel(s) to the new Selector.
2019-02-27 13:50:36.016 INFO  io.netty.channel.nio.NioEventLoop - Migrated 0 channel(s) to the new Selector.
2019-02-27 13:50:49.906 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@21f0d42d.
2019-02-27 13:50:49.906 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@8836b33.
2019-02-27 13:50:49.908 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@5bb72d7c.
2019-02-27 13:50:49.906 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@51838af8.
2019-02-27 13:50:49.913 INFO  io.netty.channel.nio.NioEventLoop - Migrated 1 channel(s) to the new Selector.
2019-02-27 13:50:49.913 INFO  io.netty.channel.nio.NioEventLoop - Migrated 0 channel(s) to the new Selector.
2019-02-27 13:50:49.913 INFO  io.netty.channel.nio.NioEventLoop - Migrated 1 channel(s) to the new Selector.
2019-02-27 13:50:49.913 INFO  io.netty.channel.nio.NioEventLoop - Migrated 1 channel(s) to the new Selector.
2019-02-27 13:50:49.946 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@5131c2fa.
2019-02-27 13:50:49.946 WARN  io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@530b16ca.
2019-02-27 13:50:49.949 INFO  io.netty.channel.nio.NioEventLoop - Migrated 1 channel(s) to the new Selector.
2019-02-27 13:50:49.949 INFO  io.netty.channel.nio.NioEventLoop - Migrated 1 channel(s) to the new Selector.
```

**Comment by normanmaurer** [comment]
@xzzh999 any reproducer ?

**Comment by xzzh999** [comment]
@normanmaurer 

use: io.netty: netty-all 4.1.24.Final

almost at the time of 1~2 hours after startup a pool but do nothing, here is the simple code snapshot:
```
final EventLoopGroup group = new NioEventLoopGroup();
final Bootstrap strap = new Bootstrap();

strap.group(group).channel(NioDatagramChannel.class);
poolMap = new AbstractChannelPoolMap<InetSocketAddress, FixedChannelPool>() {
	@Override
	protected FixedChannelPool newPool(InetSocketAddress key) {
		return new FixedChannelPool(strap.remoteAddress(key), new DeviceClientPoolHandler(), MAX_CONNECTION_CHANNEL_SIZE);
	}
};
```

**Comment by normanmaurer** [comment]
@xzzh999 so you not even serve any traffic ?

**Comment by xzzh999** [comment]
@normanmaurer  very low traffic, there are about 20 remote endpoints, but only 2 are alive.

**Comment by normanmaurer** [comment]
unfortunally I will need some kind of "full reproducer" that I can run.

**Comment by normanmaurer** [comment]
@xzzh999 ping

**Comment by xzzh999** [comment]
@normanmaurer 

Sorry for the late reply...

I found some memory leak of release the bytebuf message at the read callback function, after i fixed this leak, it seems ```the CPU is getting normal```. Though its still print the follow messages: 
```
Selector.select() returned prematurely 512 times in a row;

...
```

I'm not sure if this associated...

**Comment by normanmaurer** [comment]
@xzzh999 this log should still not show up usually... how often you see this ?

**Comment by xzzh999** [comment]
@normanmaurer 

about 20~30 min

**Comment by normanmaurer** [comment]
@xzzh999 can you retest with latest 4.1 branch and see if it is still a problem ?

**Comment by jamesdbloom** [comment]
If it helps I have noticed as I increase the number of event loop threads the number of error I see goes up roughly in proportion.  
As I increase 
threads: 25 to 65 (2.6x)  
errors increase: 10 to 20 (2.1x)
As I increase 
threads: 65 to 80 (1.23x)
errors increase: 21 to 28 (1.3x)

I am seeing these error while running the MockServer build, for example, https://buildkite.com/mockserver/mockserver/builds/1012 for repo: https://github.com/mock-server/mockserver

This is a reproducer but perhaps not the most helpful one.

**Comment by afelino** [comment]
I've met the same problem on Android on 4.1.82.Final. Do you need such a reproducer?

**Comment by apkelly** [comment]
I too am seeing this error on a device running Oreo

> 11-01 22:07:02.567  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.580  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@b16c460.
11-01 22:07:02.582  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.597  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@71461de.
11-01 22:07:02.597  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.609  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@893c68c.
11-01 22:07:02.610  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.622  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@a80bdea.
11-01 22:07:02.623  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.635  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@6fcbf78.
11-01 22:07:02.636  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.648  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@6a4ceb6.
11-01 22:07:02.649  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.660  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@cfa5b24.
11-01 22:07:02.661  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.672  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@6272042.
11-01 22:07:02.673  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.684  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@1140590.
11-01 22:07:02.685  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.696  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@58afe8e.
11-01 22:07:02.697  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.708  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@8dbeabc.
11-01 22:07:02.709  3393  4917 I NioEventLoop: Migrated 1 channel(s) to the new Selector.
11-01 22:07:02.720  3393  4917 W NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@43c759a.

I'm unable to reproduce this, but we use Netty indirectly through Ktor v1.6.8
